### ISSUE TITLE
S3: Too much data for declared Content-Length

### ISSUE THREAD

**Issue by tustvold** [localstack/localstack#10003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are seeing intermittent failures in CI with a rather opaque error message - https://github.com/apache/arrow-rs/issues/5283

```
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/http/asgi.py", line 548, in handle_http
    await response.write(packet)
  File "/opt/code/localstack/localstack/http/asgi.py", line 302, in write
    await self.send({"type": "http.response.body", "body": data, "more_body": True})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 179, in app_send
    await self.send(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 136, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

I have never been able to reproduce this locally, so it could be something funny with the way Github Actions handles proxying for containers, but it is intermittent and doesn't correspond with any change to our code that I am aware of.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run -d -p 4566:4566 localstack/localstack:3.0.1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket
```

Source - https://github.com/apache/arrow-rs/blob/master/.github/workflows/object_store.yml#L138

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 3.0.1
```

### Anything else?

https://github.com/localstack/localstack/issues/2582 is possibly related but was a while back

**Comment by bentsku** [comment]
Hi @tustvold and thanks for the report.

Sorry to hear it's causing flakiness. I'm suspecting some kind of race condition in how we handle read/write locks and file position. The error seems to indicate that when we're returning data from the S3 implementation, we might return more than what the calculated content length of the file seems to be be (S3 `GetObject`always returns the `Content-Length` header), with maybe a file position changing which would trigger a bigger read than expected.

I haven't look at the failures yet, it could be either getting a full file or some range requests as well (as they return a content-length too). I'll investigate more on our locking mechanism and if we can improve something, and try to setup a way to reproduce this kind of issue. 

Or it might be something else! I'll keep you updated, I'm really sorry for this creating some issue on your side!

**Comment by tustvold** [comment]
Thank you for the prompt response, and absolutely no worries, sorry I can't provide a more focused reproducer :sweat_smile:

**Comment by bentsku** [comment]
I finally managed to reproduce the issue locally, only in a flaky manner as well, but somewhat consistently, by running the LocalStack container with only 1 vCPU. 

I could reproduce the issue very often with `3.0.1`, but not anymore with `3.0.2` nor `latest`.

After checking the logs and the changeling between `3.0.1` and `3.0.2`, there is nothing that jumps as being responsible for the issue. However, I am now wondering is this issue is in S3 or our actually forwarding of DynamoDB-local responses.

Would it be possible to update to `3.0.2` and see if that fixes your issue too?

And then, if possible and if not too much trouble, we've fixed some more issues with S3 since `3.0.2`, and we will have a tentative release date for `3.1.0` as January 25th, and it would be great to update then. Sorry for all the trouble!

Please keep me posted about `3.0.2`! Thanks!

**Comment by tustvold** [comment]
Sadly we are still seeing failures with 3.0.2 - https://github.com/apache/arrow-rs/actions/runs/7530250446/job/20496212065

I appreciate your help with this, it's a tricky one for sure 😅

**Comment by bentsku** [comment]
Hi @tustvold, I've tried having a look at the latest actions runs since you've removed the DynamoDB workaround for LocalStack, could that have solved the issue? I'm not seeing flakes anymore, but please feel free to correct me, I wish we could get to the bottom of this 😬 I'm still not 100% sure it is an S3 issue as much as a DynamoDB one (maybe in our proxying of the requests).

**Comment by tustvold** [comment]
I have not seen this crop up recently either, happy for you to close this. Thank you for investigating, I'll let you know if it starts happening again...

**Comment by bentsku** [comment]
No problem! Feel free to re-open if it starts again, I'll try pushing it further then. I hope that's the end of it!

**Comment by yenchenLiu** [comment]
Sorry, I still suffer from this
```
LocalStack version: 3.1.1.dev
2024-02-18T22:48:41.074502840Z LocalStack Docker container id: 3c1b3a15d3ef
2024-02-18T22:48:41.074509006Z LocalStack build date: 2024-02-12
2024-02-18T22:48:41.074510798Z LocalStack build git hash: a7a70c384

2024-02-19T01:07:49.436 ERROR --- [-functhread4] hypercorn.error            : Error in ASGI Framework
2024-02-19T01:07:49.441836956Z Traceback (most recent call last):
2024-02-19T01:07:49.441838831Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/asgi.py", line 549, in handle_http
2024-02-19T01:07:49.441840706Z     await response.write(packet)
2024-02-19T01:07:49.441842164Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/asgi.py", line 303, in write
2024-02-19T01:07:49.441843623Z     await self.send({"type": "http.response.body", "body": data, "more_body": True})
2024-02-19T01:07:49.441845289Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 179, in app_send
2024-02-19T01:07:49.441846664Z     await self.send(
2024-02-19T01:07:49.441847873Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 137, in stream_send
2024-02-19T01:07:49.441849206Z     await self._send_h11_event(h11.Data(data=event.data))
2024-02-19T01:07:49.441850456Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 243, in _send_h11_event
2024-02-19T01:07:49.441851998Z     data = self.connection.send(event)
2024-02-19T01:07:49.441853164Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441854331Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
2024-02-19T01:07:49.441855664Z     data_list = self.send_with_data_passthrough(event)
2024-02-19T01:07:49.441856873Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441858039Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
2024-02-19T01:07:49.441859373Z     writer(event, data_list.append)
2024-02-19T01:07:49.441860498Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
2024-02-19T01:07:49.441861748Z     self.send_data(event.data, write)
2024-02-19T01:07:49.441862873Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
2024-02-19T01:07:49.441864123Z     raise LocalProtocolError("Too much data for declared Content-Length")
2024-02-19T01:07:49.441865414Z h11._util.LocalProtocolError: Too much data for declared Content-Length
2024-02-19T01:07:49.441866664Z 
2024-02-19T01:07:49.441867748Z During handling of the above exception, another exception occurred:
2024-02-19T01:07:49.441868956Z 
2024-02-19T01:07:49.441870039Z Traceback (most recent call last):
2024-02-19T01:07:49.441894748Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
2024-02-19T01:07:49.441898206Z     await app(scope, receive, send, sync_spawn, call_soon)
2024-02-19T01:07:49.441899914Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
2024-02-19T01:07:49.441901331Z     await self.app(scope, receive, send)
2024-02-19T01:07:49.441902539Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/asgi.py", line 75, in __call__
2024-02-19T01:07:49.441903789Z     return await self.adapter(scope, receive, send)
2024-02-19T01:07:49.441904956Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441906123Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/asgi.py", line 491, in __call__
2024-02-19T01:07:49.441907373Z     return await self.handle_http(scope, receive, send)
2024-02-19T01:07:49.441908581Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441909664Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/asgi.py", line 562, in handle_http
2024-02-19T01:07:49.441910956Z     await response.close()
2024-02-19T01:07:49.441912164Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/asgi.py", line 314, in close
2024-02-19T01:07:49.441913414Z     await self.send({"type": "http.response.body", "body": b"", "more_body": False})
2024-02-19T01:07:49.441914789Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 189, in app_send
2024-02-19T01:07:49.441916122Z     await self.send(EndBody(stream_id=self.stream_id))
2024-02-19T01:07:49.441917289Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 139, in stream_send
2024-02-19T01:07:49.441918581Z     await self._send_h11_event(h11.EndOfMessage())
2024-02-19T01:07:49.441919747Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 243, in _send_h11_event
2024-02-19T01:07:49.441921081Z     data = self.connection.send(event)
2024-02-19T01:07:49.441922247Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441923372Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
2024-02-19T01:07:49.441924622Z     data_list = self.send_with_data_passthrough(event)
2024-02-19T01:07:49.441925747Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T01:07:49.441926872Z   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 527, in send_with_data_passthrough
2024-02-19T01:07:49.441928122Z     raise LocalProtocolError("Can't send data when our state is ERROR")
2024-02-19T01:07:49.441929372Z h11._util.LocalProtocolError: Can't send data when our state is ERROR
```

Usually it occurs when performing parallel operations, where data is frequently uploaded and downloaded.

**Comment by bentsku** [comment]
Hello @yenchenLiu and thanks for the report.

Would you have a bit more information in how to reproduce? Are you using any other services than S3?
Thanks!

**Comment by tustvold** [comment]
FWIW I am seeing this fairly consistently in the object_store CI again :cry:

**Comment by bentsku** [comment]
Hi @yenchenLiu! We've just merged a new fix which should prevent this issue from happening anymore. You can give it a go by pulling `localstack/localstack:latest`. I'll close the issue, feel free to comment if you still encounter any issue and I'll re-open! Thanks!
