### ISSUE TITLE
bug: EventBridge Scheduler Cron Jobs Not Running in LocalStack

### ISSUE THREAD

**Issue by zoetaka38** [localstack/localstack#10239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello LocalStack Team,

I am encountering an issue with the EventBridge Scheduler's cron jobs not executing as expected in LocalStack. The same setup works flawlessly when deployed on AWS cloud, which suggests the issue is localized to the LocalStack environment.

**Issue Description**:

- I am trying to schedule a Lambda function to run at regular intervals using EventBridge's cron feature.
- The scheduler rules are created using Python's Boto3 library, targeting a Lambda function for execution.
- Upon checking with AWS CLI, the EventBridge rule appears to be in an ENABLED state, indicating it has been successfully created.
- The IAM Role required for the Lambda function to execute under EventBridge has been properly set up. Given that this configuration works without issues in the actual AWS environment, it is unlikely to be the source of the problem.
- While the EventBridge rule itself seems to be operational, the scheduled executions are not triggering the Lambda function as they do in AWS.

**Steps to Reproduce**:

- Create an EventBridge rule using Boto3 with a cron expression for scheduling.
- Attach a Lambda function to the rule as the target.
- Ensure the rule is in an ENABLED state and the IAM Role permissions are correctly configured.
- Observe that the Lambda function does not get triggered at the scheduled times in LocalStack, despite working in AWS.
-  have verified that the setup is identical between my LocalStack environment and AWS, so the discrepancy in behavior is quite puzzling.

Could you please provide any insights or suggestions on how to troubleshoot this issue further? Any assistance in resolving this would be greatly appreciated, as it is critical for our development and testing processes.

Thank you for your support.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

**Steps to Reproduce**:

- run LocalStack using docker-compose.yml
- Create an EventBridge rule using Boto3 with a cron expression for scheduling.
- Attach a Lambda function to the rule as the target.
- Ensure the rule is in an ENABLED state and the IAM Role permissions are correctly configured.
- Observe that the Lambda function does not get triggered at the scheduled times in LocalStack, despite working in AWS.
-  have verified that the setup is identical between my LocalStack environment and AWS, so the discrepancy in behavior is quite puzzling.

### Environment

```markdown
- OS: Mac M3
- LocalStack: latest
```

**Comment by hkaiser25** [comment]
I have created an EventBridge schedule in localstack to execute a lambda every minute and it's not working for me as well.

**Comment by vitormomberg** [comment]
I have the same problem here, but i'm trying to send a sqs message, and it doesn't working.
I'm using AWS SDK for Java and I achieved create schedule but it does not working on schedule expression expected.

**Comment by seanamos** [comment]
This is because Eventbridge Scheduler isn't fully implemented in localstack: https://github.com/localstack/localstack/issues/9861

The APIs exist, they return the expected response codes, but they are basically stubs. Actual scheduler execution functionality doesn't exist yet.

Yes, we ran into this as well and it was quite confusing because all the documentation indicates that the scheduler is implemented. Eventually found the above github issue.

**Comment by magalenyo** [comment]
Any news regarding this issue?

**Comment by maxhoheiser** [comment]
Hi, we are mixing two separate services here in the issues:
A:  on the one hand EventBrdige supports rules with targets that are not triggered based on incoming events that match the pattern attached to the rule but based on a schedule (cron or regex)
B: on the other hand we have EventBrdige Scheduler that can be used to schedule triggering target services.

A, scheduled rules are fully implemented and we released last week with LocalStack 3.5 our brand new EventBridge v2 version that amongst many other improvements and parity fixes also addresses scheduled rules. You can use the new EventBridge by setting the environment variable `PROVIDER_OVERRIDE_EVENTS=v2` - please give it a try and let us know if there are any other issues you encounter with scheduled rules.

B, regarding EventBrdige Scheduler, as correctly stated above not yet fully implemented but is currently actively developed and will be released in the near future.

**Comment by vishal-kotecha-baps** [comment]
Why this was closed? as of today, 3rd August, 2024, i am having the same issue mentioned. I am using latest version of localstack  3.6.0 on Macbook M3 PRO and created an EventBridge Scheduler, setting a Lambda function as a target using latest AWS java SDK bom 2.26.25. I do not see the function getting triggered.

**Comment by bking0** [comment]
Is there an ETA on this or a way to activate the scheduler?  I have yesterday's build and still doesn't seem to be working
LocalStack version: 4.0.4.dev5
LocalStack build date: 2024-12-03
LocalStack build git hash: 56db7ca1d

**Comment by LeonardoCampello-dev** [comment]
any update?

**Comment by Neelabhra08** [comment]
Any updates on this?
