### ISSUE TITLE
bug: hanging during `docker run` with docker v4.30.0

### ISSUE THREAD

**Issue by cbortz** [localstack/localstack#10832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to start localstack, using `DEBUG=1 localstack start`, the process hangs and never starts localstack.

Here's a snippet:

```
2024-05-15T17:24:12.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.configure_localstack_container:_mount_machine_file
2024-05-15T17:24:12.021 DEBUG --- [  MainThread] l.u.c.docker_cmd_client    : Run container with cmd: ['docker', 'run', '--rm', '--entrypoint', 'sh', '-p', '0.0.0.0:53:53/udp', '-p', '0.0.0.0:53:53', 'localstack/localstack', '-c', 'echo test123']
2024-05-15T17:24:12.021 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: ['docker', 'run', '--rm', '--entrypoint', 'sh', '-p', '0.0.0.0:53:53/udp', '-p', '0.0.0.0:53:53', 'localstack/localstack', '-c', 'echo test123']
```
[full-log.txt](https://github.com/localstack/localstack/files/15327178/full-log.txt)

### Expected Behavior

Localstack should start.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    EAGER_SERVICE_LOADING=1 SERVICES="s3" localstack start -d

### Environment

```markdown
- OS: MacOS Sonoma 14.4.1
- LocalStack: 3.4.0 (via Homebrew)
- Docker: 4.30.0
```

### Anything else?

Rolling Docker back to v4.29.0 works fine.

**Comment by MarcelStranak** [comment]
Hello @cbortz,

The issue should be addressed in [Docker Desktop 4.30.0](https://docs.docker.com/desktop/release-notes/#for-mac).

A similar case was reported in https://github.com/localstack/localstack/issues/10340 and resolved by the Docker team as seen in https://github.com/docker/for-mac/issues/7207.

I recommend trying our minimal S3 image with `docker pull localstack/localstack:s3-latest`, tailored to your specific S3 service usage.

**Comment by Igormandello** [comment]
@cbortz

I'm having the same issue on Docker Desktop v4.30.0 and was able to solve it going to my **Docker Desktop Settings** > **Resources** > **Network** and disable `Use kernel networking for UDP`.

The interesting part is that it was suggested [here](https://github.com/docker/for-mac/issues/7207#issuecomment-2004556158), and didn't seem to fix the problem in that version.

**Comment by MarcelStranak** [comment]
Hi @cbortz, @Igormandello, this issue is resolved in the latest version (https://github.com/localstack/localstack/pull/11011)
