### ISSUE TITLE
bug: ApiGatewayV2 redirecting to ALB adds content-encoding: gzip to the header automatically

### ISSUE THREAD

**Issue by bdowson** [localstack/localstack#11665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have localstack api gateway (I imported from my production AWS api gateway) that is pointing to ALB integrations (also running on localstack).

When I try and access the route `/accounts/health` with my load balancer via the browser I get the correct response. When I try and access the same route with my api gatway I get this error:
`Failed to load resource: net::ERR_CONTENT_DECODING_FAILED`
Furthermore, the same route on Postman gives me this error:
`Error: Parse Error: Invalid character in chunk size`

However, when I curl the api gateway I get the correct response.

### Curl of loadbalancer:
```
curl -v http://local-alb.elb.localhost.localstack.cloud/accounts/health
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to local-alb.elb.localhost.localstack.cloud (127.0.0.1) port 80 (#0)
> GET /accounts/health HTTP/1.1
> Host: local-alb.elb.localhost.localstack.cloud
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 10 Oct 2024 09:39:27 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/8.1.9RC1
< Cache-Control: private, must-revalidate
< pragma: no-cache
< expires: -1
< 
* Connection #0 to host local-alb.elb.localhost.localstack.cloud left intact
OK
```

### Curl of ApiGateway:
```
curl -v https://e7bf5050.execute-api.localhost.localstack.cloud:4566/local/accounts/health
*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to e7bf5050.execute-api.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost.localstack.cloud
*  start date: Sep  6 00:00:00 2024 GMT
*  expire date: Dec  5 23:59:59 2024 GMT
*  subjectAltName: host "e7bf5050.execute-api.localhost.localstack.cloud" matched cert's "*.execute-api.localhost.localstack.cloud"
*  issuer: C=AT; O=ZeroSSL; CN=ZeroSSL RSA Domain Secure Site CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x6298baf9e650)
> GET /local/accounts/health HTTP/2
> Host: e7bf5050.execute-api.localhost.localstack.cloud:4566
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: TwistedWeb/24.3.0
< date: Thu, 10 Oct 2024 09:44:18 GMT
< content-type: text/html; charset=UTF-8
< cache-control: private, must-revalidate
< content-encoding: gzip
< expires: -1
< pragma: no-cache
< x-powered-by: PHP/8.1.9RC1
< content-length: 2
< apigw-requestid: 6263b540
< 
* Connection #0 to host e7bf5050.execute-api.localhost.localstack.cloud left intact
OK
```
One thing that sticks out to me is that the `content-encoding: gzip ` is added to the api gateway response, which shouldn't be there.

### Expected Behavior

I should be able to see the correct response on postman or the browser without error.

For reference, here is the same request on my ALB and API gateway from AWS:

### load balancer:
```
curl -v xxxxxxxx.us-east-1.elb.amazonaws.com/ 
*   Trying x.x.x.x:80...
* TCP_NODELAY set
* Connected to xxxxxxxxxx.us-east-1.elb.amazonaws.com (x.x.x.x) port 80 (#0)
> GET /accounts/health HTTP/1.1
> Host: xxxxxxxxx.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 10 Oct 2024 09:19:50 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: nginx
< X-Powered-By: PHP/8.1.9RC1
< Cache-Control: private, must-revalidate
< pragma: no-cache
< expires: -1
< 
* Connection #0 to host xxxxxxx.us-east-1.elb.amazonaws.com left intact
OK
```

### api gateway
```
curl -v https://xxxxxxx.execute-api.us-m/staging/accounts/health
*   Trying x.x.x.x:443...
* TCP_NODELAY set
* Connected to xxxxxxxx.execute-api.us-east-1.amazonaws.com (x.x.x.x) port 443 (#0)
....
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x606a106ca650)
> GET /staging/accounts/health HTTP/2
> Host: xxxxxxxxxx.execute-api.us-east-1.amazonaws.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Thu, 10 Oct 2024 09:20:54 GMT
< content-type: text/html; charset=UTF-8
< content-length: 2
< server: nginx
< apigw-requestid: fbViogxQoAMEJbw=
< x-powered-by: PHP/8.1.9RC1
< cache-control: private, must-revalidate
< pragma: no-cache
< expires: -1
< 
* Connection #0 to host xxxxxx.execute-api.us-east-1.amazonaws.com left intact
OK
```

You can see that the load balancer response matches what I have in localstack, but the api gateway response does not. No `content-encoding: gzip` is added to the AWS api gateway response, which is not the case with localstack.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose up localstack -d`

```
localstack:
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - PERSISTENCE=1
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - PROVIDER_OVERRIDE_APIGATEWAY=next_gen
    networks:
      app_network:
        ipv4_address: 10.0.2.20
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/localstack-data:/var/lib/localstack"
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Route:
```
{
            "ApiKeyRequired": false,
            "AuthorizationType": "NONE",
            "RouteId": "93a4f500",
            "RouteKey": "ANY /accounts/{proxy+}",
            "Target": "integrations/3c7318e9"
        },
```
Integration:
```
{
            "ConnectionType": "INTERNET",
            "IntegrationId": "3c7318e9",
            "IntegrationMethod": "ANY",
            "IntegrationType": "HTTP_PROXY",
            "IntegrationUri": "http://local-alb.elb.localhost.localstack.cloud/accounts/{proxy}",
            "PayloadFormatVersion": "1.0",
            "TimeoutInMillis": 30000
        },
```

The code is simply a laravel application returning a text response:
```
Route::get('/health', function () {
    return response('OK');
});
```
### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- LocalStack: 
  LocalStack version: 3.8.1.dev1
  LocalStack Docker image sha: localstack/localstack-pro@sha256:d6afe6c70964904446267b1ad8cc207936d169bf2f398442add3ce094c78ed31
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by bentsku** [comment]
Hello @bdowson and thanks a lot for your report! I'm glad to see you are using our new implementation of API Gateway.

Just to be sure I'm going in the right direction, I believe your Load Balancer, or more precisely your application behind it, might return gzip data if you set the right header.

I believe our issue stems from the fact that our default HTTP client will fetch the data in API Gateway from the Load Balancer, accepting gzip, decoding the body but leaving the `Content-Encoding` header. 

Just to be sure, could you run the same curl command against your Load Balancer and API Gateway in AWS but with the following flag? Just to confirm both will return gzip if you ask them to. 
The flag: `-H "Accept-Encoding: gzip"`. 

In any case, our gzip handling is wrong and I'm currently working on it! It seems AWS API Gateway will not decode a gzip body and will not make it available to `ResponseParameters` mapping by default, and will pass it as it to the client. But just want to double check before considering it fixed. Thank you!

**Comment by bdowson** [comment]
Hi @bentsku, thanks for looking into this for me!

I did the curl requests again with the `-H "Accept-Encoding: gzip"` header on the AWS LB and API Gateway, and here are the results:

### Load Balancer
```
curl -H "Accept-Encoding: gzip" -v [LB URL]

*   Trying x.x.x.x:80...
* TCP_NODELAY set
* Connected to xxxxxxxxxx.us-east-1.elb.amazonaws.com x.x.x.x) port 80 (#0)
> GET /accounts/health HTTP/1.1
> Host: xxxxxxxxx.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.68.0
> Accept: */*
> Accept-Encoding: gzip
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 11 Oct 2024 01:10:36 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: nginx
< X-Powered-By: PHP/8.1.9RC1
< Cache-Control: private, must-revalidate
< pragma: no-cache
< expires: -1
< Content-Encoding: gzip
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 22)
* Failed reading the chunked-encoded stream
* Closing connection 0
```

### API Gateway
```
curl -H "Accept-Encoding: gzip" -v [API GW URL]
*   Trying x.x.x.x:443...
* TCP_NODELAY set
...
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5aa0eb87a650)
> GET /staging/accounts/health HTTP/2
> Host: xxxxxxx.execute-api.us-east-1.amazonaws.com
> user-agent: curl/7.68.0
> accept: */*
> accept-encoding: gzip
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Fri, 11 Oct 2024 01:11:07 GMT
< content-type: text/html; charset=UTF-8
< content-length: 2
< server: nginx
< apigw-requestid: fdguxifjIAMEV3Q=
< x-powered-by: PHP/8.1.9RC1
< cache-control: private, must-revalidate
< pragma: no-cache
< expires: -1
< 
* Connection #0 to host xxxxxx.execute-api.us-east-1.amazonaws.com left intact
OK
```

Oddly enough the load balancer fails but the API Gateway still works.

**Comment by bentsku** [comment]
Thank you so much @bdowson! 🙏 this is great, it seems to show that for Private Integrations (ELB), AWS API Gateway automatically decodes the body and remove the `Content-Encoding`. I tried it against a regular `HTTP_PROXY` integration and here it keeps the body encoded as `gzip`. 

I'll make this fix and notify you once it is available in our `latest` image. Thank you again for taking the time to test it further! 🙏

**Comment by bentsku** [comment]
Hello @bdowson, I've merged the potential fix for your issue and it should now be available in the `latest` image. Could you please pull `localstack/localstack-pro:latest` and see if it solves your issue?

If not, would it be possible to give us a minimal reproducible sample that we could run to reproduce the issue? I think what I've done should do it, but in case it doesn't, it would help making sure we would fix it at once.

Thank you very much, please tell me if it does fix it 🙏

**Comment by bdowson** [comment]
Hi @bentsku , thanks for the update. I pulled the latest localstack but now I can't import my AWS API:

```
Error importing API Gateway: An error occurred (InternalError) when calling the ImportApi operation (reached max retries: 4): exception while calling apigatewayv2.ImportApi: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/provider.py.enc", line 151, in import_api
    def import_api(A,context,body,basepath=_A,fail_on_warnings=_A,**B):return A._import_api(context,body,basepath=basepath)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/provider.py.enc", line 160, in _import_api
    else:N=G.create_api(Name=P.get('title')or'',ProtocolType='HTTP',Tags={A[c]:A['x-amazon-apigateway-tag-value']for A in H.get(_c,[])},**L);D=N[_C]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the CreateApi operation (reached max retries: 4): exception while calling apigatewayv2.CreateApi: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/provider.py.enc", line 115, in create_api
    X='credentialsArn';W='ApiGatewayManaged';V='$request.method $request.path';I=request;H='RouteSelectionExpression';D=context;from localstack.pro.core.services.apigatewayv2.next_gen.execute_api.websockets_legacy.websocket_async_handler import get_websocket_message_handler_next_gen as Y;C=short_uid();Z=I.get(_V)or{};J=Z.get(TAG_KEY_CUSTOM_ID)
                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/websockets_legacy/websocket_async_handler.py.enc", line 11, in <module>
    from localstack.services.apigateway.helpers import get_event_request_context
ImportError: cannot import name 'get_event_request_context' from 'localstack.services.apigateway.helpers' (/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/helpers.py)
```

I am still able to import in the previous image, so there is something different about this image and importing.

**Comment by cloutierMat** [comment]
Hi @bdowson,
There was a wrong import statement in a `latest` build that got published earlier today. It has since been fixed and pulling the latest image again should solve this issue.

Please let us know if that solved the issue.

**Comment by bdowson** [comment]
Hi @cloutierMat , deleting the image and repulling it allows me to import again, thanks!

@bentsku Now it doesn't seem to detect the created api gateway at all:

After I import my API, I do this to get my URL:
```
$ awslocal apigatewayv2 get-apis
{
    "Items": [
        {
            "ApiEndpoint": "http://8eb4ecd5.execute-api.localhost.localstack.cloud:4566",
            "ApiId": "8eb4ecd5",
            "ApiKeySelectionExpression": "$request.header.x-api-key",
            "CorsConfiguration": {
                "AllowHeaders": [
                    "*"
                ],
                "AllowMethods": [
                    "*"
                ],
                "AllowOrigins": [
                    "*"
                ],
                "ExposeHeaders": [
                    "*"
                ]
            },
            "CreatedDate": "2024-10-15T05:46:40.904000+00:00",
            "DisableExecuteApiEndpoint": false,
            "Name": "XpedigoAPI_v2",
            "ProtocolType": "HTTP",
            "RouteSelectionExpression": "$request.method $request.path",
            "Tags": {},
            "Version": "2024-09-25 01:18:37UTC"
        }
    ]
}
```
Then I curl it:
```
$ curl -v http://8eb4ecd5.execute-api.localhost.localstack.cloud:4566/accounts/health
*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to 8eb4ecd5.execute-api.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
> GET /accounts/health HTTP/1.1
> Host: 8eb4ecd5.execute-api.localhost.localstack.cloud:4566
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 NOT FOUND
< Server: TwistedWeb/24.3.0
< Date: Tue, 15 Oct 2024 05:51:35 GMT
< Content-Type: application/json
< Content-Length: 86
< 
* Connection #0 to host 8eb4ecd5.execute-api.localhost.localstack.cloud left intact
{"message": "The API id '8eb4ecd5' does not correspond to a deployed API Gateway API"}
```

I tried both http and https, recreating the api, and even clicking on it directly via app.localstack.cloud, still get the same error: `The API id 'xxxxxxxxx' does not correspond to a deployed API Gateway API`

**Comment by cloutierMat** [comment]
I am glad to hear that pulling the image solved this issue @bdowson.

Can you also confirm the stage related to this deployment? `awslocal apigatewayv2 get-stages --api-id=8eb4ecd5`

If the value for `StageName` is not `$default` you should also include the stage name in the url `https://8eb4ecd5.execute-api.localhost.localstack.cloud:4566/<StageName>/accounts/health`

**Comment by bdowson** [comment]
Hi @cloutierMat , I just tried with adding the stage name and I still get the same error:

curl -v http://421d5aeb.execute-api.localhost.localstack.cloud:4566/local/accounts/health
*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to 421d5aeb.execute-api.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
> GET /local/accounts/health HTTP/1.1
> Host: 421d5aeb.execute-api.localhost.localstack.cloud:4566
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 NOT FOUND
< Server: TwistedWeb/24.3.0
< Date: Tue, 15 Oct 2024 06:25:28 GMT
< Content-Type: application/json
< Content-Length: 86
< 
* Connection #0 to host 421d5aeb.execute-api.localhost.localstack.cloud left intact
{"message": "The API id '421d5aeb' does not correspond to a deployed API Gateway API"}
```

**Comment by cloutierMat** [comment]
Can you confirm the stage is pointing to the deployment? You should be able to see the deployment id in the stage description.
```
▶ awslocal apigatewayv2 get-stage --api-id 76513afe --stage-name local
{
    "CreatedDate": "2024-10-15T06:31:47.248667Z",
    "DefaultRouteSettings": {
        "DetailedMetricsEnabled": false
    },
    "DeploymentId": "90118a12",
    "LastUpdatedDate": "2024-10-15T06:31:47.248667Z",
    "RouteSettings": {},
    "StageName": "local",
    "StageVariables": {},
    "Tags": {}
}
```

**Comment by bdowson** [comment]
Seems to be:

```
$ awslocal apigatewayv2 get-stage awslocal apigatewayv2 get-stage --api-id 421d5aeb --stage-name local
{
    "CreatedDate": "2024-10-15T06:24:07.439578+00:00",
    "DefaultRouteSettings": {
        "DetailedMetricsEnabled": false
    },
    "DeploymentId": "d954f32f",
    "LastUpdatedDate": "2024-10-15T06:24:07.439578+00:00",
    "RouteSettings": {},
    "StageName": "local",
    "StageVariables": {
        "baseurl": "local-alb.elb.localhost.localstack.cloud",
        "env": "local"
    },
    "Tags": {}
}
```

**Comment by cloutierMat** [comment]
It does appear to be in order.

Can you share with me a sample of the api you are importing that can reproduce the issue?

**Comment by bdowson** [comment]
Sure, even a trimmed down version of my api json will tell me that it doesnt correspond to a deployed api:
```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "api",
    "version" : "2024-09-25 01:18:37UTC"
  },
  "servers" : [ {
    "url" : "https://local-api.asdf.com/{basePath}",
    "variables" : {
      "basePath" : {
        "default" : "local"
      }
    }
  } ],
  "paths" : {
    "/accounts/{proxy+}" : {
      "parameters" : [ {
        "name" : "proxy+",
        "in" : "path",
        "description" : "Generated path parameter for proxy+",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      } ],
      "x-amazon-apigateway-any-method" : {
        "responses" : {
          "default" : {
            "description" : "Default response for ANY /accounts/{proxy+}"
          }
        },
        "x-amazon-apigateway-integration" : {
          "payloadFormatVersion" : "1.0",
          "type" : "http_proxy",
          "httpMethod" : "ANY",
          "uri" : "http://asdf.com/accounts/{proxy}",
          "connectionType" : "INTERNET"
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      
    }
  },
  "x-amazon-apigateway-cors" : {
    "allowMethods" : [ "*" ],
    "allowHeaders" : [ "*" ],
    "exposeHeaders" : [ "*" ],
    "maxAge" : 0,
    "allowCredentials" : false,
    "allowOrigins" : [ "*" ]
  },
  "x-amazon-apigateway-importexport-version" : "1.0"
}
```

**Comment by bentsku** [comment]
Hello @bdowson! As we are working towards our `4.0` release, we've done some internal refactoring that might break persistence between versions. Could you please delete your state folder which seems to be located at `/localstack-data` following your Docker-compose, and give it a try again? 

Using the `latest` image, I cannot reproduce the issue with the small template you've created:

```bash
$ awslocal apigatewayv2 import-api --body file://t.json
{
    "ApiEndpoint": "08acb4f0.execute-api.localhost.localstack.cloud:4566",
    "ApiId": "08acb4f0",
    "CorsConfiguration": {
        "AllowHeaders": [
            "*"
        ],
        "AllowMethods": [
            "*"
        ],
        "AllowOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "*"
        ]
    },
    "Name": "api",
    "ProtocolType": "HTTP",
    "Tags": {},
    "Version": "2024-09-25 01:18:37UTC"
}
$ awslocal apigatewayv2 create-stage --api-id 08acb4f0 --stage-name dev --auto-deploy
{
    "AutoDeploy": true,
    "CreatedDate": "2024-10-15T09:42:26Z",
    "StageName": "dev"
}
$ curl http://08acb4f0.execute-api.localhost.localstack.cloud:4566/dev/accounts/test
# returns nothing, the request is forwarded to `asdf.com` like the sample and we can see in the LocalStack logs it works
```

**Comment by bdowson** [comment]
Hi @bentsku , after trying it on a fresh VM with the latest version of localstack I am happy to report that it works as expected now when I curl it from the command line! 

One thing though, not sure why, but when I try a GET request using postman using the same URL I still get this error:
```
GET https://7b36535b.execute-api.localhost.localstack.cloud:4566/local/accounts/health
Error: Parse Error: Invalid character in chunk size
Request Headers
User-Agent: PostmanRuntime/7.42.0
Accept: */*
Cache-Control: no-cache
Postman-Token: a5c91e67-bbaa-4c43-b827-aca43a1974cd
Host: 7b36535b.execute-api.localhost.localstack.cloud:4566
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

Is there a configuration that needs to be changed on the localstack side?

**Comment by bentsku** [comment]
@bdowson, great to hear it works! Does it work from the browser like initially reported? 

Yes, I wasn't sure we would get everything right with this fix as it a bit of stab in the dark, as I don't have the exact same setup as you. 
Could you share the response headers?

**Comment by bdowson** [comment]
@bentsku  Yes, it works on the browser now too thanks!

postman doesn't output the response headers unfortunately, but the headers I get back when I curl it from the command line are this:
```
HTTP/2 200 
server: TwistedWeb/24.3.0
date: Tue, 15 Oct 2024 12:04:50 GMT
content-type: text/html; charset=UTF-8
cache-control: private, must-revalidate
expires: -1
pragma: no-cache
x-powered-by: PHP/8.1.9RC1
content-length: 2
apigw-requestid: 32f031ec

```

**Comment by bentsku** [comment]
Oh, that is very weird if the browser works but not postman 🤔 

Could you also run the curl command with `-H "Accept-Encoding: gzip, deflate, br"` please?

**Comment by bdowson** [comment]
I tried curl with those headers and it didn't seem to like it:

```
$ curl -H "Accept-Encoding: gzip, deflate, br" -v https://50217dc3.execute-api.localhost.localstack.cloud:4566/local/accounts/health

*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to 50217dc3.execute-api.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost.localstack.cloud
*  start date: Sep  6 00:00:00 2024 GMT
*  expire date: Dec  5 23:59:59 2024 GMT
*  subjectAltName: host "50217dc3.execute-api.localhost.localstack.cloud" matched cert's "*.execute-api.localhost.localstack.cloud"
*  issuer: C=AT; O=ZeroSSL; CN=ZeroSSL RSA Domain Secure Site CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x59dba485f650)
> GET /local/accounts/health HTTP/2
> Host: 50217dc3.execute-api.localhost.localstack.cloud:4566
> user-agent: curl/7.68.0
> accept: */*
> accept-encoding: gzip, deflate, br
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: TwistedWeb/24.3.0
< date: Wed, 16 Oct 2024 04:49:35 GMT
< content-type: text/html; charset=UTF-8
< cache-control: private, must-revalidate
< content-encoding: gzip
< expires: -1
< pragma: no-cache
< x-powered-by: PHP/8.1.9RC1
< content-length: 22
< apigw-requestid: 14f0284c
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 22)
* stopped the pause stream!
* Connection #0 to host 50217dc3.execute-api.localhost.localstack.cloud left intact
* 
```

**Comment by bentsku** [comment]
Hello @bdowson! I think I found why the issue is still happening in Postman but not with curl or the browser, and this might be related to HTTP2 vs HTTP1.1, and the `Transfer-Encoding` header. We have a fix up, and I'll ping you here once it is available. Thanks!
