### ISSUE TITLE
S3 Event Not Invoking Lambda

### ISSUE THREAD

**Issue by miles-po** [localstack/localstack#2007]
**To reproduce (replace with actual lambda and ARN):**

1. Create S3 bucket
  * `awslocal s3 mb s3://dp-garage-lake-us`
2. Make a simple lambda (currently using Node, so created with a Docker container by LS)
3. Confirm lambda is published and get the lambda's ARN
  * `awslocal lambda list-functions`
4. Set the bucket notification
  * `awslocal s3api put-bucket-notification-configuration --bucket dp-garage-lake-us --notification-configuration '{"LambdaFunctionConfigurations":[{"Events":["s3:ObjectCreated:*"],"LambdaFunctionArn":"arn:aws:lambda:us-east-1:000000000000:function:S3IngestToKinesis"}]}'`
5. Confirm bucket notification
  * `awslocal s3api get-bucket-notification-configuration --bucket dp-garage-lake-us`
6. Upload file
  * `awslocal s3 cp test.json s3://dp-garage-lake-us/some/path/to/test.json`

**Expected:**
Lambda is invoked with file metadata

**Actual:**
No invocation from the logs. No errors shown. Event is not fired.

**Notes:**
Lambda works when invoked manually with `awslocal lambda invoke …`

Code appears to in place, but is not getting invoked for some reason. Perhaps because the lambda is being invoked in its own container?
https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L182

**Comment by whummer** [comment]
Thanks for the detailed report, @miles-po . I was following the exact steps you listed above, and for me the Lambda actually does get triggered when putting the file on S3.

```
$ awslocal s3 cp test.json s3://dp-garage-lake-us/some/path/to/test.json
upload: ./test.json to s3://dp-garage-lake-us/some/path/to/test.json
```
Then, in the LocalStack terminal:
```
2020-03-02T15:42:55:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response from this function will be returned to caller
2020-03-02T15:42:56:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create --user=root --entrypoint=/tmp/5aa0b845.sh --dns 127.0.0.1 -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "localstack/lambda:nodejs10.x" "handler.hello")";docker cp "/tmp/localstack/zipfile.f31e0b66/." "$CONTAINER_ID:/var/task"; docker cp /tmp/5aa0b845.sh $CONTAINER_ID:/tmp/5aa0b845.sh; docker start -ai "$CONTAINER_ID";
```

Is this, by any chance, already fixed in the `latest` version? If not, then I think we should create a small isolated example to reproduce this issue. Are you seeing any relevant logs in the LocalStack container with `DEBUG=1` enabled? Thanks

**Comment by wkhatch** [comment]
I don't know why this is closed, but it's still a problem on latest localstack
