### ISSUE TITLE
Getting "The specified bucket does not exist" when running Localstack inside docker-compose

### ISSUE THREAD

**Issue by miguepintor** [localstack/localstack#2154]
Hi there,
Although Localstack looks quite promising, since a couple of weeks ago our team is a bit blocked due to an issue we are experiencing with CloudFormation.
Any help would be more than welcome.

Having a docker-compose like this:

```
version: '3'

services:
  gateway:
    image: app
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=localkey
      - AWS_SECRET_ACCESS_KEY=localsecret

  localstack:
    container_name: localstack
    image: localstack/localstack
    expose:
      - "4567-4599"
    ports:
      - "4567-4599:4567-4599"
    environment:
      - SERVICES=iam, lambda, s3, cloudformation, sqs, sts
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=true
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - DEBUG=1
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Gateway container it is just a container with several tools pre-installed like (awscli ... ) to be used as an entry point for the inner network.

From that gateway container we can successfully run :
```
aws --endpoint-url=http://localstack:4572 s3api create-bucket --bucket serverlessdeploy --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
```

Even upload object to it (hitting http://localstack:4572 with the following parameters):
```
{
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 2768 more bytes>,
  Bucket: 'mybucket',
  Key: 'whatever/local/1584035954811-2020-03-12T17:59:14.811Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'h003I5m1ox/MQ+ia+9zyvGQ38kOrHTI62EVft/J6aIc=' }
}
```

But when we try to create an stack hitting CloudFormation (http://localstack:4581) with the following params:
```
{
  StackName: 'whatever',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'http://localstack:4572/mybucket/whatever/local/1584035954811-2020-03-12T17:59:14.811Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
}
```

We receive the following error:
```
"CreateStack" (404) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>localstack:4572</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```

## Additional Info:
 
Docker daemon it is not in the host machine

Operating System: Linux/4.14.146-119.123.amzn2.x86_64 
Localstack Version: latest (0.10.8)
Aws cli Version:  aws-cli/1.18.20 Python/3.5.3 botocore/1.15.20
Docker Version: 19.03.7, build 7141c199a2

## Edit:
If we run same steps locally (having docker daemon in the host machine) we face the following *different* issue:
```
HTTP 502
```
And the stack:
```
2020-03-13T12:45:02:ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to fetch template body (code 403) from URL http://localstack:4572/mybucket/whatever/local/1584103485885-2020-03-13T12:44:45.885Z/compiled-cloudformation-template.json Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 247, in forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 172, in forward_request
    modified_request = transform_template(req_data)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 70, in transform_template
    template_body = get_template_body(req_data)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 115, in get_template_body
    raise Exception('Unable to fetch template body (code %s) from URL %s' % (status_code, url))
Exception: Unable to fetch template body (code 403) from URL http://localstack:4572/mybucket/whatever/local/1584103485885-2020-03-13T12:44:45.885Z/compiled-cloudformation-template.json
```

Thanks in advance.

**Comment by miguepintor** [comment]
In my opinion for me there is clearly an internal networking issue inside the docker container Localstack/localstack

**Comment by xxx87370343** [comment]
I also face a similar problem. The communication between cloudformation and S3 seems to be a bit problem. ·No such bucket· often appears. Or where am I doing wrong to cause this error?

**Comment by whummer** [comment]
Thanks for reporting @miguepintor .

The error you posted indicates a permission denied error, not a networking error per se.
```
Exception: Unable to fetch template body (code 403) from URL http://localstack:4572/mybucket/whatever/local/1584103485885-2020-03-13T12:44:45.885Z/compiled-cloudformation-template.json
```

In fact, we've recently pushed a change in #2148 that could be related to this issue. Can you please do a `docker pull localstack/localstack` and give it another try? Thanks

**Comment by david-mk-lawrence** [comment]
I also have this exact issue. My configuration is almost identical to @miguepintor.

I'm using serverless framework + localstack, and trying to deploy to localstack, but keep getting hung up on the Cloudformation create/update steps with the same error.

It seems to specifically be an issue with specifying `TemplateUrl` (`TemplateBody` still works for example).

I tried pulling the latest localstack image @whummer, but still getting the same error.

**Comment by miguepintor** [comment]
@whummer I tried with the latest:

```
$ docker pull localstack/localstack:latest
latest: Pulling from localstack/localstack
Digest: sha256:f4658065fc07b24a7a8fd42620658bed39a5ebbd92fb039ca4b4dd1dd2ad76ba
```

And same issue:

```
Error response for CloudFormation action "CreateStack" (404) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>localstack:4572</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```

Also @whummer take into account that is a 404 not a 403. Maybe this could help us to identify the issue.

Many thanks for your support.

**Comment by david-mk-lawrence** [comment]
Did some work trying to debug this today. The issue seems to be in the backend Cloudformation moto server (maybe that was obvious?).

I pulled down localstack and have been running and modifying a local version to try and debug it. I added a bunch of logging statements in `generic_proxy.py` to see what's going on.

I can see that the requests made to create the bucket and objects all succeed at `http://127.0.0.1:4563`, which is the host and port for the backend moto server. Then the `POST` made to the backend cloudformation server throws the error. 

The TemplateUrl contains the custom hostname (`localstack` in this case), and the frontend s3 port (`4572`). So I'm wondering if the moto server is having trouble resolving that host and port since it's being run inside of the docker container.

**Comment by amar02041988** [comment]
Is fix available for this? I am facing the same error. Specified bucket doesnot exist when trying to use localstack's cloudformation with serverless-localstack plugin.

**Comment by amar02041988** [comment]
Request to localstack experts to please resolve this issue.

**Comment by whummer** [comment]
Thanks for the update @miguepintor @david-mk-lawrence @amar02041988 . I was able to reproduce this issue, and believe it should be fixed via #2182 . Can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!

**Comment by amar02041988** [comment]
Doing a pull. Will test and let you know.

**Comment by miguepintor** [comment]
@whummer I tried again with:
```
Pulling localstack (localstack/localstack:)...
latest: Pulling from localstack/localstack
b9bba2329739: Pull complete
Digest: sha256:f02c93fd0ea277c87bfb550e10a6602af49bf1b6ac070c90ea8a264682c2ba89
```
The problem is still reproducible :(

Thanks for your support.

**Comment by miguepintor** [comment]
@whummer taking a look into the trace I can see this:
`<BucketName>localstack:4572</BucketName>\n`
Is that correct? shouldn't be "mybucket" or "localstack:4572/mybucket" ?

**Comment by amar02041988** [comment]
@whummer Its failing with same error.

**Comment by whummer** [comment]
Another quick update was pushed in #2185 @miguepintor @david-mk-lawrence @amar02041988 , can you please give it another try with the `latest` version. Thanks for your help in resolving this.

**Comment by miguepintor** [comment]
It works!!

With this image:
```
latest: Pulling from localstack/localstack
Digest: sha256:1ecc3fb13d62b490b87ac6e6de881ecd946eaf7a62a6f7110b1b36844c52367b
```
It is working now.
Good job, thx for your support!

**Comment by amar02041988** [comment]
Yeah, cloudformation stack now worked successfully as i have used serverless framework with serverless-localstack plugin and sls deploy --stage=local worked without errors. But when i access my deployed API(API Gateway+lambda), the API Gateway endpoint gets hung forever. This might be separate issue. But am again stuck.
Anyways, thanks for quick resolution.

**Comment by amar02041988** [comment]
Finally got the response from API gateway as well, after few tries. Thanks

**Comment by ecolotko** [comment]
@whummer 

It seems that after breaking change in **v0.11.5** (the single edge service via `4566` port) the problem has returned.

I'm using Serverless framework within the Docker container:
```yml
service: ${env:LAMBDA_FUNCTION}

frameworkVersion: "^2.*"

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stackName: ${self:custom.stage}-${self:service}
  stage: ${self:custom.stage}
  tracing:
    lambda: true
  versionFunctions: false
  deploymentPrefix: aws-lambda
  deploymentBucket:
    name: ${self:custom.stage}-deploy
    serverSideEncryption: AES256

functions:
  LocalFunction:
    handler: live/index.handler
    name: ${self:custom.stage}-${self:service}
    provisionedConcurrency: 1
    reservedConcurrency: 1
    runtime: nodejs12.x
    tracing: PassThrough

custom:
  localstack:
    debug: true
    docker:
      sudo: false
    edgePort: 4566
    host: http://localstack
    lambda:
      mountCode: true
    stages: [local]
  stage: local
```

I run lambda inside the `node:12` container:
```shell
npx serverless deploy
```

`serverless-deployment-bucket` plugin takes care of creating the S3 bucket:
```shell
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 404 0.043s 0 retries] headBucket({ Bucket: 'local-deploy' })
Serverless: Creating deployment bucket 'local-deploy'...
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 200 0.027s 0 retries] createBucket({
  Bucket: 'local-deploy',
  ACL: 'private',
  CreateBucketConfiguration: { LocationConstraint: 'us-east-1' }
})
Serverless: [AWS s3 200 0.018s 0 retries] headBucket({ Bucket: 'local-deploy' })
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 404 0.074s 0 retries] getBucketEncryption({ Bucket: 'local-deploy' })
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 200 0.027s 0 retries] putBucketEncryption({
  Bucket: 'local-deploy',
  ServerSideEncryptionConfiguration: {
    Rules: [
      {
        ApplyServerSideEncryptionByDefault: { SSEAlgorithm: 'AES256', KMSMasterKeyID: undefined }
      },
      [length]: 1
    ]
  }
})
Serverless: Applied SSE (AES256) to deployment bucket
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 200 0.022s 0 retries] getBucketVersioning({ Bucket: 'local-deploy' })
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 200 0.02s 0 retries] getBucketAccelerateConfiguration({ Bucket: 'local-deploy' })
```

and I can see that it was indeed created by running command on local machine (outside the container)
```shell
$ aws --endpoint http://localhost:4566 s3api list-buckets --profile localstack
{
    "Buckets": [
        {
            "Name": "local-deploy",
            "CreationDate": "2020-12-08T22:30:51+00:00"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

but CloudFormation doesn't see the bucket
```shell
Serverless: Using custom endpoint for CloudFormation: http://localstack:4566
Serverless: [AWS cloudformation 400 0.025s 0 retries] describeStacks({ StackName: 'local-test-lambda' })
Serverless: Using custom endpoint for S3: http://localstack:4566
Serverless: [AWS s3 200 0.032s 0 retries] listObjectsV2({
  Bucket: 'local-deploy',
  Prefix: 'aws-lambda/test-lambda/local'
})
...
Serverless: Using custom endpoint for CloudFormation: http://localstack:4566
Serverless: Overriding S3 templateUrl to http://localstack:4566
Serverless: [AWS cloudformation 404 0.069s 0 retries] createStack({
  StackName: 'local-test-lambda',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'http://localstack:4566/local-deploy/aws-lambda/test-lambda/local/1607466652056-2020-12-08T22:30:52.056Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The specified bucket does not exist
      at /lambda/data/test-lambda/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:1314:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
From `localstack` container logs:
```shell
2020-12-08T22:13:14:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateStack" (404) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>localstack:4566</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```
`<BucketName>localstack:4566</BucketName>` looks weird.

**P.S.**: I'm on the most recent `localstack` version:
```shell
$ docker image ls localstack/localstack
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              82e92a0f5ac6        2 hours ago         646MB
```

**Comment by ezekiel25-17** [comment]
Having similar issue with the latest version. Rolled back to '1.2.0' to workaround
