### ISSUE TITLE
Lambda triggered by SQS event source doesn't delete SQS message

### ISSUE THREAD

**Issue by El-Gor-do** [localstack/localstack#2536]
# Type of request: This is a ...

[X] bug report

# Detailed description
I am running Windows 10, Docker Desktop Community 2.3.0.3 (45519) and LocalStack 0.11.2 Docker image. I have a .Net Core 3.1 lambda with a SQS event source. When I send a message to SQS, if my lambda's execution duration is longer than ~2880ms then the SQS message stays in-flight and is not deleted, causing the message to be processed again after the message's visibility timeout expires. If the lambda's duration is shorter than ~2880ms then the SQS message is deleted, as expected.

## Expected behavior
If my lambda doesn't throw an exception then the SQS message should always be deleted.

## Actual behavior
The SQS message is only deleted if the lambda's execution duration is shorter than ~2880ms. I don't know the exact duration that triggers this bug because each invocation runs for a slightly different duration but I can send many SQS messages, each containing a value specifying the lambda's delay time, in order to observe the duration and whether the message is deleted.

# Steps to reproduce
[AwsLambda.zip](https://github.com/localstack/localstack/files/4755081/AwsLambda.zip)
Attached a Visual Studio 2019 solution to reproduce the bug. In the LambdaDotNetCoreRuntime subdirectory, run the following batch files:
* "1 install dotnet tools.bat" to install the Amazon Lambda tools
* "2 start localstack.bat" to start LocalStack using docker-compose
* "3 create AWS services.bat" to build the Lambda package, create SQS queue, create Lambda function and SQS event source
* "4 send sqs message.bat" to send a SQS message containing a delay value in milliseconds. The lambda will trigger and pretend to do work by delaying for this duration.

At step 4, observe the Duration value when the lambda finishes execution. If duration is shorter than approximately 2880ms then the SQS message is deleted, otherwise the message stays in-flight.

## Command used to start LocalStack
"docker-compose -f docker-compose.yml up" using the attached LambdaDotNetCoreRuntime\docker-compose.yml file

**Comment by whummer** [comment]
Thanks for reporting this issue @El-Gor-do . Please note that we have recently done some substantial changes/improvements to the SQS API, and we're using a different backend now. Do you think you could do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Thanks, much appreciated.

**Comment by metersk** [comment]
I'm having the same issue w/ `latest`

**Comment by El-Gor-do** [comment]
I have tested my attached repro with 0.11.3 and the same problem occurs as with 0.11.2

**Comment by metersk** [comment]
fwiw... 
`0.11.2` does not delete the messages and keeps reprocessing them in an infinite loop

`0.11.3`/`latest` errors out with: 
`botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.`
so it looks like it is at least attempting to delete the messages.

**Comment by whummer** [comment]
Thanks again for the update @metersk @El-Gor-do . This should be fixed in latest - an integration test has been added in #2709 to cover this functionality. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? In case the problem still persists, then please add a small, self-contained code snippet here (sequence of `awslocal` shell commands, or other self-contained test code file) to help reproduce this issue. Thanks!

**Comment by El-Gor-do** [comment]
I have tested localstack/localstack:latest (0.11.3) following the same steps as described in my original post. In "4 send sqs message.bat" if I set delayMs=5770, the message is successfully processed but is not deleted from the queue so this bug is not resolved.

The attached log is from my Localstack container. Lines 1-26 are Localstack starting up. Lines 27-42 are the messages after running "4 send sqs message.bat".
[aws log.txt](https://github.com/localstack/localstack/files/4928539/aws.log.txt)

**Comment by matthall88** [comment]
I am having the exact same issue with latest localstack (installed via pip, run with "localstack start")

create queue
create lambda
create event source
post to queue via node API (from within another running lambda)
The subscribed lambda is triggered and executes successfully, but the message is not deleted and then the lambda re-invokes

```
WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f5a3cc98f70>(None) failed: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 155, in _run
    callback and callback(result, func_arn, event, error=raised_error, dlq_sent=dlq_sent)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 373, in delete_messages
    sqs_client.delete_message_batch(QueueUrl=queue_url, Entries=entries)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.
```
