### ISSUE TITLE
Edge service fails when calling concurrently

### ISSUE THREAD

**Issue by nrgraham23** [localstack/localstack#2873]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
We have integration tests which create SSM parameters and KMS keys and aliases.  When I allow the tests (junit) to run with 16 threads, the edge service becomes unresponsive and I have to stop and start the docker container.  If I run the tests with a single thread, the edge service handles the requests well.  If I use the ports associated with SSM and KMS directly, I am able to successfully run the tests with 16 threads and do not encounter errors.

## Expected behavior
I should be able to hit the edge service rather than using the other service ports directly.

## Actual behavior
The edge service becomes unresponsive and requests time out.

# Steps to reproduce

## Command used to start LocalStack
Docker container with compose file:

version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR="/tmp/localstack/data"
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

SSM:

   ```
    PutParameterRequest request = new PutParameterRequest()
        .withDataType("text")
        .withType("SecureString")
        .withName(name)
        .withValue(value)
        .withTier("Standard")
        .withOverwrite(true);

    ssmClient.putParameter(request);
```

KMS key:

```
    CreateKeyRequest req = new CreateKeyRequest();
    CreateKeyResult result = kmsClient.createKey(req);

    String targetKeyId = result.getKeyMetadata().getArn();
```

KMS Alias:

```
    CreateAliasRequest request = new CreateAliasRequest().withAliasName(aliasName).withTargetKeyId(targetKeyId);
    kmsClient.createAlias(request);

```

**Comment by whummer** [comment]
Thanks for reporting this issue @nrgraham23 . We do have some limitations with large number of concurrent requests, but I'm surprised that it is already happening for 16 worker threads only. Are your tests only using SSM and KMS, or any other services as well?

This should now (hopefully) be fixed in #2876 - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version? Please report here if the problem persists. Thanks!

**Comment by nrgraham23** [comment]
Thanks for responding to this so quickly @whummer.  I pulled the latest docker and ran our tests again and it definitely did better, but the edge service still gets knocked over.

Each test creates 2 KMS keys, 2 KMS aliases, and 18 SSM parameters.  The parameters and KMS aliases use an update if they already exist.
