### ISSUE TITLE
Lambdas fail to start, works in AWS. 

### ISSUE THREAD

**Issue by svintit** [localstack/localstack#2990]
# Type of request: This is a bug:

[x] bug report
[ ] feature request

# Detailed description
There is an issue with python lambdas not working with a zip file provided which works in AWS. This happens when creating a function with `aws lambda` pointed at localstack. 

The main issue seems to be numpy (possibly other packages) and this is because of the alpine image used to build localstack. 

The zip contains numpy and other packages.

```shell
  File "/tmp/localstack/zipfile.a7453991/lambda_tasks/data_ingress.py", line 4, in <module>
    import pandas
  File "/tmp/localstack/zipfile.a7453991/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.8 from "/opt/code/localstack/.venv/bin/python"
  * The NumPy version is: "1.19.2"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/localstack/zipfile.a7453991/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 963, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 793, in set_function_code
    raise ClientError('Unable to get handler function from lambda code.', e)
localstack.services.awslambda.lambda_api.ClientError: Unable to get handler function from lambda code.
```

...

## Expected behavior
Lambda create-function succeeds. 

...

## Actual behavior
Lambda create-function fails.

...

# Steps to reproduce
```shell
    aws --endpoint-url="$ENDPOINT_URL" lambda create-function \
        --function-name "sqs-pull-function" \
        --zip-file "fileb:///tmp/localstack-init/lambda/sqs-pull-function.zip" \
        --handler "lambda_function.lambda_handler" \
        --runtime "python3.8" \
        --region "us-east-1" \
        --memory-size "128" \
        --role _
```
Reduced zip file: https://drive.google.com/file/d/1bAdnmVTjbt9VfKaKe27LIb-7w_-gk0cR/view?usp=sharing

## Command used to start LocalStack
Start through a helm chart. https://github.com/everpeace/helm-charts/tree/master/localstack

`helm install localstack <path-to-chart>`

...

**Comment by macnev2013** [comment]
Hey @svintit . Thanks for reporting the issue.
Can you give it a try putting your code in the root folder instead of sub folder?

**Comment by svintit** [comment]
@macnev2013 thanks for the reply. Do you mean the zipfile itself or the code inside the zipfile?

**Comment by svintit** [comment]
The zipfile location is a volumeMount. All the code and packages are at the root of the zip and the code in its normal default location of the`lambda_function` file. The only subfolders that exist are each individual package folders.

**Comment by whummer** [comment]
Hi @svintit , thanks for the update. Can you please confirm that this exact same Lambda handler zip file has been used in your test? Looks like the zip file contains a folder `sqs-pull-function/` at the root level, which then contains the package folders. (i.e., the handler would have to be something like `sqs-pull-function.lambda_function.lambda_handler`)

Also, we have just pushed a small change in #2999 to disable the validation of the handler file upon Lambda creation (which is more in line with real AWS behavior). Can you please give it another try after pulling the `latest` image again? Thanks

**Comment by svintit** [comment]
@whummer 

I've tried updating to latest image, still have the same issue. 

I've tried using `sqs-pull-function.lambda_function.lambda_handler` as the handler, same issue. 

I've tried compressing just the files and folders inside `sqs-pull-function` instead of the `sqs-pull-function` folder itself, same issue. 

Exact same stack trace each time.

**Comment by whummer** [comment]
Hi @svintit , upon closer inspection, it seems that you are using the local Lambda executor (`LAMBDA_EXECUTOR=local`) - is that right? Have you tried using the default Docker executor (`LAMBDA_EXECUTOR=docker`)? We'll work on reproducing and pushing a fix for the local executor shortly. Thanks

**Comment by svintit** [comment]
@whummer ive indeed tried setting `docker` as the lambda executor, nothing changes unfortunately.

I've tried `docker-reuse` also, causing other errors where the service no longer spins up at all.

**Comment by svintit** [comment]
I know this is a bit of a pain, I've been down every road I could come up with with no progress including even the possibility of the packages being installed on glibc while localsfack running on alpine would have musl. Unfortunately I had no way to get around this and try packaging on musl, ended up in continuous "rabbit hole" errors.

I do appreciate your time here!

**Comment by macnev2013** [comment]
Hey @svintit , Thanks for the update. Is it possible to share your deployment files/commands? Thanks.

**Comment by svintit** [comment]
@macnev2013 I provided everything in the initial issue but i'll add again here for convenience. 

```shell
    ENDPOINT_URL="http://localhost:4566"

    aws --endpoint-url="$ENDPOINT_URL" lambda create-function \
        --function-name "sqs-pull-function" \
        --zip-file "fileb:///tmp/localstack-init/lambda/sqs-pull-function.zip" \
        --handler "lambda_function.lambda_handler" \
        --runtime "python3.8" \
        --region "us-east-1" \
        --memory-size "128" \
        --role _
```

Reduced zip file: https://drive.google.com/file/d/1bAdnmVTjbt9VfKaKe27LIb-7w_-gk0cR/view?usp=sharing

**Comment by macnev2013** [comment]
Hey @svintit, Thanks for providing the files.

I checked it with real AWS and localstack (helm, docker-compose, running from code) and on both I am getting the same error:  `An error occurred (RequestEntityTooLargeException) when calling the CreateFunction operation: Request must be smaller than 69905067 bytes for the CreateFunction operation`.
Also we have removed all the check for lambda creation except length constraints (which is behaviour we noticed in real AWS).

I have used `values.yaml` and command provided by you.
Am i missing something?

Is it possible on gitter to discuss in detail?

Thanks

**Comment by svintit** [comment]
Hi @macnev2013, thanks for your time here. Apologies I also just remembered this error and it is true, but only when you provide the zip directly, if you provide it through s3 the limit is larger.

Apologies again.

**Comment by macnev2013** [comment]
Hey @svintit , Thanks for the update.
I tried to reproduce the issue. But it is working as expected (exactly like AWS). Am I missing something?

**Exporting Variable**
`$ ENDPOINT_URL="http://localhost:4566"`

**Creating Bucket**
`$ aws --endpoint-url="$ENDPOINT_URL" s3 mb s3://test`
**Output:**
`make_bucket: test`

**Uploading Zip to Bucket**
`$ aws --endpoint-url="$ENDPOINT_URL" s3 cp sqs-pull-function.zip s3://test`
**Output:**
`upload: ./sqs-pull-function.zip to s3://test/sqs-pull-function.zip `

**Creating Lambda function with handler 1:**
```
$ aws --endpoint-url="$ENDPOINT_URL" lambda create-function \
      --function-name "sqs-pull-function1" \
      --code S3Bucket=test,S3Key=sqs-pull-function.zip \
      --handler "lambda_function.lambda_handler" \
      --runtime "python3.8" \
      --region "us-east-1" \
      --memory-size "128" \
      --role _

```
**Output:**
```
{
    "FunctionName": "sqs-pull-function1",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:sqs-pull-function1",
    "Runtime": "python3.8",
    "Role": "_",
    "Handler": "lambda_function.lambda_handler",
    "CodeSize": 53949945,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2020-09-28T14:39:39.733+0000",
    "CodeSha256": "ZP+2Ge2eZ6YrfY+J2Nwj4MEdf/nVv9RQ+zESdBvU4F4=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "6f9cb3af-6549-47f5-96e9-1d325897d65c",
    "State": "Active",
    "LastUpdateStatus": "Successful"
}

```

**Creating Lambda function with handler 2:**
```
$ aws --endpoint-url="$ENDPOINT_URL" lambda create-function \
      --function-name "sqs-pull-function2" \
      --code S3Bucket=test,S3Key=sqs-pull-function.zip \
      --handler "sqs-pull-function.lambda_function.lambda_handler" \
      --runtime "python3.8" \
      --region "us-east-1" \
      --memory-size "128" \
      --role _

```
**Output:**
```
{
    "FunctionName": "sqs-pull-function2",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:sqs-pull-function2",
    "Runtime": "python3.8",
    "Role": "_",
    "Handler": "sqs-pull-function.lambda_function.lambda_handler",
    "CodeSize": 53949945,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2020-09-28T14:41:23.451+0000",
    "CodeSha256": "ZP+2Ge2eZ6YrfY+J2Nwj4MEdf/nVv9RQ+zESdBvU4F4=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "52d63ff5-1678-4a68-9204-65ccc67c4728",
    "State": "Active",
    "LastUpdateStatus": "Successful"
}
```

**Comment by svintit** [comment]
Thanks for the time @macnev2013 

That is bizarre, i've tried both handlers and I get the same error with both, is my machine missing something somehow? 

I ran the exact command you did (outside of a script) and still getting the same error. This makes 0 sense to me. 

```
An error occurred (500) when calling the CreateFunction operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```

```
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 973, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 800, in set_function_code
    raise ClientError('Unable to get handler function from lambda code.', e)
localstack.services.awslambda.lambda_api.ClientError: Unable to get handler function from lambda code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 987, in create_function
    return e.get_response()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 143, in get_response
    return error_response(self.msg, self.code)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 635, in error_response
    return aws_responses.flask_error_response_json(msg, code=code, error_type=error_type)
  File "/opt/code/localstack/localstack/utils/aws/aws_responses.py", line 15, in flask_error_response_json
    'Type': 'User' if code < 500 else 'Server',
TypeError: '<' not supported between instances of 'ModuleNotFoundError' and 'int'
[2020-09-28 16:32:10 +0000] [21] [ERROR] Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 794, in set_function_code
    lambda_handler = exec_lambda_code(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 593, in exec_lambda_code
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 580, in exec_lambda_code
    handler_module = imp.load_source(lambda_id, lambda_file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/localstack/lambda_script_l_2813b7e7.py", line 3, in <module>
    from lambda_tasks import LambdaTasks
ModuleNotFoundError: No module named 'lambda_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 973, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 800, in set_function_code
    raise ClientError('Unable to get handler function from lambda code.', e)
localstack.services.awslambda.lambda_api.ClientError: Unable to get handler function from lambda code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 987, in create_function
    return e.get_response()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 143, in get_response
    return error_response(self.msg, self.code)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 635, in error_response
    return aws_responses.flask_error_response_json(msg, code=code, error_type=error_type)
  File "/opt/code/localstack/localstack/utils/aws/aws_responses.py", line 15, in flask_error_response_json
    'Type': 'User' if code < 500 else 'Server',
TypeError: '<' not supported between instances of 'ModuleNotFoundError' and 'int'
```

**Comment by macnev2013** [comment]
Can you try changing `pullPolicy` in helm `value.yaml`?
Something like this:
```
image:
  repository: localstack/localstack
  tag: latest
  pullPolicy: Always
```

**Comment by dingwen150** [comment]
> Thanks for the time @macnev2013
> 
> That is bizarre, i've tried both handlers and I get the same error with both, is my machine missing something somehow?
> 
> I ran the exact command you did (outside of a script) and still getting the same error. This makes 0 sense to me.
> 
> ```
> An error occurred (500) when calling the CreateFunction operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 973, in create_function
>     result = set_function_code(func_details.code, lambda_name)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 800, in set_function_code
>     raise ClientError('Unable to get handler function from lambda code.', e)
> localstack.services.awslambda.lambda_api.ClientError: Unable to get handler function from lambda code.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 987, in create_function
>     return e.get_response()
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 143, in get_response
>     return error_response(self.msg, self.code)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 635, in error_response
>     return aws_responses.flask_error_response_json(msg, code=code, error_type=error_type)
>   File "/opt/code/localstack/localstack/utils/aws/aws_responses.py", line 15, in flask_error_response_json
>     'Type': 'User' if code < 500 else 'Server',
> TypeError: '<' not supported between instances of 'ModuleNotFoundError' and 'int'
> [2020-09-28 16:32:10 +0000] [21] [ERROR] Exception on /2015-03-31/functions [POST]
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 794, in set_function_code
>     lambda_handler = exec_lambda_code(
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 593, in exec_lambda_code
>     raise e
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 580, in exec_lambda_code
>     handler_module = imp.load_source(lambda_id, lambda_file)
>   File "/usr/lib/python3.8/imp.py", line 171, in load_source
>     module = _load(spec)
>   File "<frozen importlib._bootstrap>", line 702, in _load
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/tmp/localstack/lambda_script_l_2813b7e7.py", line 3, in <module>
>     from lambda_tasks import LambdaTasks
> ModuleNotFoundError: No module named 'lambda_tasks'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 973, in create_function
>     result = set_function_code(func_details.code, lambda_name)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 800, in set_function_code
>     raise ClientError('Unable to get handler function from lambda code.', e)
> localstack.services.awslambda.lambda_api.ClientError: Unable to get handler function from lambda code.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 987, in create_function
>     return e.get_response()
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 143, in get_response
>     return error_response(self.msg, self.code)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 635, in error_response
>     return aws_responses.flask_error_response_json(msg, code=code, error_type=error_type)
>   File "/opt/code/localstack/localstack/utils/aws/aws_responses.py", line 15, in flask_error_response_json
>     'Type': 'User' if code < 500 else 'Server',
> TypeError: '<' not supported between instances of 'ModuleNotFoundError' and 'int'
> ```

you can also try pulling the latest docker image:
`docker image pull localstack/localstack:latest`

**Comment by whummer** [comment]
Thanks for the pointers @macnev2013 @dingwen150 @svintit . Indeed it looks like an older image is being used here - please report here if the problem still persists after pulling the `latest` image from Docker Hub. Thanks for your help in resolving this.
