### ISSUE TITLE
localstack 0.7.5 overwritten?! and SQS bug introduced!

### ISSUE THREAD

**Issue by jens-meiss** [localstack/localstack#308]
Hi,

it seems someone pushed a newer version of 0.7.5 to dockerhub. I worked with 0.7.5 last week (2017-08-31) and i cleaned my local repos, so that 0.7.5 was pulled again today from dockerhub, but now all my SQS tests fail because i got the internal port and not the external port of the queue resource, when i create a new queue.

* 0.0.0.0:32959->4576
  * the external port is 32959 
* but int the CreateQueueResult i got: http://localhost:4576/123456789012/test-queue
* instead of: http://localhost:32959/123456789012/test-queue

If you look on the tags page:

* https://hub.docker.com/r/localstack/localstack/tags/

you see that 0.7.5 was updated 3 days ago, so its a different 0.7.5 than i got last week (8 days ago).

Why is it possible to override a released version in dockerhub? 

It works with 0.7.4 (until someone overrides this version with the current 'latest' version ;))

**Comment by whummer** [comment]
Thanks for reporting @jens-meiss , the issue with overwriting Docker image versions has been fixed in 3b16cb22614e5ccadf2444fa3fef04d3236e1f0f . Regarding the SQS port issue, can you please post the exact command you're using to start LocalStack? Thanks

**Comment by jens-meiss** [comment]
hi,

sorry that i missed that example :) 

 i'm using [testcontainers for java](https://github.com/testcontainers/testcontainers-java) to start the docker image.

In code it looks like this:

    GenericContainer genericContainer = new GenericContainer("localstack/localstack:0.7.4")
                .withExposedPorts(4567, 4568, 4569, 4570, 4571, 4572, 4573, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4582)
                .withFileSystemBind("/var/run/docker.sock", "/var/run/docker.sock", READ_WRITE)
                .waitingFor(new LogMessageWaitStrategy().withRegEx(".*Ready\\.\n"));

    genericContainer.start();
      
    final Integer mappedPort = genericContainer.getMappedPort(4576);

**Comment by whummer** [comment]
Thanks @jens-meiss . I'm not too familiar with how Testcontainers works exactly, but shouldn't the example above simply expose 0.0.0.0:4576->4576, i.e., exernal (host) port 4576 to container port 4576? In `docker run` terms that would simply be a `-p 4576:4576` flag. Where does the 32959 port come from - are you specifying it explicitly in the code, or is that some auto-generated port number?

**Comment by jens-meiss** [comment]
if you tell me where i can find that? :)

testcontainers exports random ports, so that you can work for example with SQS on 4576 while you execute SQS integration tests on your local machine ...

i just pushed a small test which runs a SQS test with 0.7.4 and 0.7.5, the 0.7.5 one will fail causes by the described issue. You just need java and maven to run it (see the README.md).

* https://github.com/jens-meiss/localstack-testcontainers-java

There is also a lot of debug output which maybe can give you a hint where the problem is.

**Comment by maksi** [comment]
Same problem in 0.8.1 (latest), 0.8.0, 0.7.5
So those who use CreateQueueResult have stuck with 0.7.4 because of that

**Comment by whummer** [comment]
This should be fixed in #440, the queue URL should now be returned with the correct external port. Can you please give it a try with the latest version @maksi @jens-meiss

**Comment by jens-meiss** [comment]
hi,

yes works again! thx :)

i have created a testcase for this issue, maybe you wan't to merge it into master:

* https://github.com/localstack/localstack/pull/446

**Comment by maksi** [comment]
I have just run it on 0.8.2 and it doesn't work for me.. returning 4576... 
Is it right version?

**Comment by whummer** [comment]
@maksi - this fix has not been released as a new version yet, please try using either the `latest` Docker image, or by cloning the repository and running the following commands to start up LocalStack with the latest code:
```
make install
make infra
```
We're planning to release a new version with this fix soon.

**Comment by maksi** [comment]
@whummer Thank you so much. Port is correct in the latest. That is great!

Unfortunately, it doesn't solve my particular issue because of the not correct hostname in a queue url.
It was real hostname (like "ip-192-168-5-86.ec2.internal") in 0.7.4 but now it's "localhost" always.
So url can't be used by a client running in another docker container (I run bunch of them by docker compose).

**Comment by whummer** [comment]
@maksi You could try using the `HOSTNAME_EXTERNAL` environment variable - see [Configuration section](https://github.com/localstack/localstack#configurations) in the README. Does that work for you?

**Comment by maksi** [comment]
@whummer I use localstack to setup testing environment for existing component. It uses queue url from CreateQueueResult. It is production code and I cannot change it for testing purposes. I think it's pretty typical use case.

Is there any reason for changing hostname to localhost after version 0.7.4 or it's just side effect of another change?

**Comment by whummer** [comment]
> You could try using the HOSTNAME_EXTERNAL environment variable

Sorry for not being clear. You don't need to change the production code - what I'm trying to say is that you could start LocalStack like this:
```
HOSTNAME_EXTERNAL=localhost make infra
```

**Comment by maksi** [comment]
@whummer Yes, HOSTNAME_EXTERNAL resolves my problem. Thanks you so much! Seems the issue can be closed.
