### ISSUE TITLE
WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: <tablename> not found in {}

### ISSUE THREAD

**Issue by suspiration** [localstack/localstack#3230]
# Type of request:
[x] bug report

# Detailed description
I have a dynamodb step in localstack running `awslocal dynamodb list-tables` will output:

```
{
    "TableNames": [
        "my_dynamodb_table"
    ]
}
```

However, when I access the table via nodeJS AWS SDK configured to point to localstack, I keep getting warning.
`WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: my_dnamodb_table not found in {}`

localstack also runs very slowly and read/writing into dynamodb takes 1-2 seconds per transaction which is ridiculously slow.
...

## Expected behavior
There should be no warning.
...

## Actual behavior
WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: <tablename> not found in {}
...

# Steps to reproduce
## Command used to start LocalStack
running localstack with docker-compose.yml

```
version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3,lambda,cloudformation,apigateway,dynamodb
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=0
    volumes:
      - ../tmp:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
AWS SDK: v2.696.0
...

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-60) by [Unito](https://www.unito.io/learn-more)

**Comment by irahulranjan** [comment]
Hi @suspiration, Thanks for reporting the issue. Can you please share the client JS code that is being used.

**Comment by irahulranjan** [comment]
Hi @suspiration, I was unable to reproduce the issue. Can you please share the client code so I can dig deeper into the issue. Also you can pull the latest version of localstack and give it a shot. If the issue still persists please reopen the issue.
Thanks

**Comment by suspiration** [comment]
I pulled latest docker image of localstack and it seems to have been resolved.  Thanks!

**Comment by jorgexgb** [comment]
`WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: my_dnamodb_table not found in {}` Im having this similar issue with the latest docker image. But the interesting part is that all the data is there. Persistence works. And I only get this issue when doing many requests.

**Comment by MarioSimou** [comment]
I came across the same issue and I managed to solve it by enabling the environment variable `DYNAMODB_SHARE_DB=1` [link](https://docs.localstack.cloud/localstack/configuration/#dynamodb). It seems that the localstack client was searching for a database table in a different region compared to the one I was expecting

**Comment by ceckhardt** [comment]
I know this issue is now closed, but I still get this error on OSX, running localstack:latest, with DYNAMODB_SHARE_DB=1 when writing batch items.
`localstack       | 2022-07-19T17:26:32.575  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.DescribeTable => 200
localstack       | 2022-07-19T17:26:33.236  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.GetItem => 200
localstack       | 2022-07-19T17:26:33.262  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.GetItem => 200
localstack       | 2022-07-19T17:26:33.411 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Unknown table: test_table not found in dict_keys([])
localstack       | 2022-07-19T17:26:33.412  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.BatchWriteItem => 500 (InternalError)
`
