### ISSUE TITLE
Startup issue for DynamoDB with certain charset system configurations

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#4456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're seeing startup issues for DynamoDB, related to incompatible charset system configurations (reported by a user on MacOS, didn't have a chance to look into it in detail yet).

Error details in this screenshot:
![image](https://user-images.githubusercontent.com/2807888/129605018-058a1c26-efc6-4d94-b160-e4f67880adc4.png)

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

-

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by GeertWille** [comment]
Having the same issue as mentioned above. Trying to run on macOS (M1) with the latest.

**Comment by sosuren** [comment]
Same issue - macOS (M1) . Tried with `0.12.16.2`, `0.12.12`

**Comment by vasigorc** [comment]
Same issue - macOS(M1). In addition to `dynamodb` not becoming available `kinesis` was terminated on start-up:

```shell
2021-08-24T13:20:19:ERROR:localstack.services.kinesis.kinesis_starter: kinesis terminated with return code -11
```

**Comment by quii** [comment]
I seem to have a similar problem, m1 too

```
AssertionError: kinesis backend has stopped
localstack_1               | 
localstack_1               | During handling of the above exception, another exception occurred:
localstack_1               | 
localstack_1               | Traceback (most recent call last):
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 105, in check_infra
localstack_1               |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 147, in check_service_health
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 140, in check_service_health
localstack_1               |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
localstack_1               |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 174, in check_kinesis
localstack_1               |     raise AssertionError("kinesis backend has stopped")
localstack_1               | AssertionError: kinesis backend has stopped
```

Mainly, dynamo won't start up for me

```
localstack_1               | Waiting for all LocalStack services to be ready
localstack_1               | 2021-08-24T14:23:58:INFO:localstack.utils.common: Restarting process (received exit code -6): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 33521 -inMemory
localstack_1            
```

**Comment by seregazhuk** [comment]
Having the same problem on m1 with charset:

```
localstack_main        | Exception in thread "main" java.lang.ExceptionInInitializerError
localstack_main        | at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:191)
localstack_main        | at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:836)
localstack_main        | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
localstack_main        | at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
localstack_main        | at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
localstack_main        | at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
localstack_main        | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
localstack_main        | at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
localstack_main        | at org.eclipse.jetty.server.Server.start(Server.java:418)
localstack_main        | at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
localstack_main        | at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
localstack_main        | at org.eclipse.jetty.server.Server.doStart(Server.java:382)
localstack_main        | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
localstack_main        | at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.start(DynamoDBProxyServer.java:83)
localstack_main        | at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:76)
localstack_main        | Caused by: java.nio.charset.IllegalCharsetNameException: l;charset=iso-8859-1
localstack_main        | at java.base/java.nio.charset.Charset.checkName(Unknown Source)
localstack_main        | at java.base/java.nio.charset.Charset.lookup2(Unknown Source)
localstack_main        | at java.base/java.nio.charset.Charset.lookup(Unknown Source)
localstack_main        | at java.base/java.nio.charset.Charset.forName(Unknown Source)
localstack_main        | at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:113)
localstack_main        | at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:69)
```

**Comment by sebastianczech** [comment]
@seregazhuk I can confirm on my M1 mac mini, that 0.12.8 is working :) the latest unfortunately not , I have the same issue as the others with dynamodb

**Comment by quii** [comment]
Tried again with 12.8 this morning

```
localstack_1               | Waiting for all LocalStack services to be ready
localstack_1               | 2021-09-27T06:39:04:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 46689 -inMemory
localstack_1               | 2021-09-27T06:39:06:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
localstack_1               | Waiting for all LocalStack services to be ready
localstack_1               | 2021-09-27T06:39:09:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 46689 -inMemory
```

It seem to keep retrying forever

**Comment by alexrashed** [comment]
@sebastianczech @GeertWille @sosuren @vasigorc @quii @seregazhuk We just released 0.13, which includes a native arm64 image. This issue should hopefully be fixed with the native execution. Could someone give it a try to verify that it now works as expected? Thanks!

**Comment by quii** [comment]
Yeah that seemed to fix it @alexrashed , thank you so much!

**Comment by alexrashed** [comment]
Great! Happy to hear that. :) Closing the issue for now.

**Comment by vasigorc** [comment]
Hey @alexrashed sorry for late answer!

The issues persists for me. I installed the recent version, as suggested:

```shell
pip install localstack -U
...
```

Running it still yields the same errors as before:

```shell
localstack start         

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.0.7

[10:48:26] starting LocalStack in Docker mode 🐳  
...
Starting mock Route53 service on http port 4566 ...
2021-11-26T15:48:50:ERROR:localstack.services.kinesis.kinesis_starter: kinesis terminated with return code -11
...
2021-11-26T15:49:22:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
2021-11-26T15:49:23:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 55031 -inMemory
Waiting for all LocalStack services to be ready
2021-11-26T15:49:28:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 55031 -inMemory
Waiting for all LocalStack services to be ready
...
```

Eventually the following error also prints out:
```shell
Waiting for all LocalStack services to be ready
Error starting infrastructure: 'NoneType' object is not subscriptable Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
api=name, print_error=print_error, expect_shutdown=expect_shutdown
File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
raise e
File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 31, in check_dynamodb
assert isinstance(out["TableNames"], list)
TypeError: 'NoneType' object is not subscriptable
```

I'm on **macOS** Monterey 12.0.1, **Chip** Apple M1.

Please let me know if you would prefer to open a new issue instead.

**Comment by whummer** [comment]
Thanks for the update @vasigorc . Can you please do a `docker pull localstack/localstack` and confirm if the problem persists with the `latest` Docker image? Thanks

**Comment by vasigorc** [comment]
Hey @whummer thank you for following-up quickly! If this is the expected output, then I think it's working 🙂 :

```shell
localstack start                                

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.0.7

[11:40:58] starting LocalStack in Docker mode 🐳                                                                                                                                                                                                             localstack.py:111
─────────────────────────────────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-26T11:40:58.625:INFO:localstack.plugins: configuring container with edge ports: [4566, 0]
Waiting for all LocalStack services to be ready
2021-11-26 16:40:59,203 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-11-26 16:40:59,204 INFO supervisord started with pid 15
2021-11-26 16:41:00,217 INFO spawned: 'infra' with pid 21
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner

LocalStack version: 0.13.0.7
LocalStack build date: 2021-11-26
LocalStack build git hash: b21178e1

Starting edge router (https port 4566)...
2021-11-26 16:41:01,278 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Ready.
[2021-11-26 16:41:01 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-11-26T16:41:01.208:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
```

**Comment by sebastianczech** [comment]
Hi @alexrashed , sorry for late answer, it's working also for me, thanks a lot :)

**Comment by johnfercher** [comment]
Hello, I'm getting this same error running on `localstack:4.0.4.dev90` on my M4 Pro now in 2025. As the same reported in 2021 using `localstack:0.12.8` works fine, I don't know what's happening...

When I run `tflocal apply` the command stuck with this error:

`
2025-01-08T14:31:37.752-0300 [DEBUG] provider.terraform-provider-aws_v4.67.0_x5: HTTP Response Received: http.response.header.content_type=application/json tf_req_id=da9b9555-b32a-8828-8048-ad384215bcd1 tf_rpc=ApplyResourceChange http.status_code=500 tf_provider_addr=registry.terraform.io/hashicorp/aws @caller=github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.26/logger.go:138 aws.operation=CreateTable aws.sdk=aws-sdk-go http.response.header.date="Wed, 08 Jan 2025 17:31:08 GMT" http.response.header.x_amzn_errortype=InternalError http.response.header.x_amz_crc32=1916568885 http.response.header.x_amzn_requestid=91ca76e5-57fd-4979-b694-5ad7af1df023 http.response.body="{\"__type\": \"InternalError\", \"message\": \"exception while calling dynamodb.CreateTable: gave up waiting for service dynamodb to start\"}" http.response.header.server=TwistedWeb/24.3.0 @module=aws aws.region=us-east-1 aws.service=DynamoDB http.duration=29536 http.response_content_length=133 tf_mux_provider="*schema.GRPCProviderServer" tf_resource_type=aws_dynamodb_table timestamp=2025-01-08T14:31:37.752-0300
`

On localstack I have these errors:

`
Restarting process (received exit code -6): ['java', '-Xmx256m', '-javaagent:/usr/lib/localstack/dynamodb-local/2/ddb-local-loader-0.1.jar', '-Djava.library.path=/usr/lib/localstack/dynamodb-local/2/DynamoDBLocal_lib', '-jar', '/usr/lib/localstack/dynamodb-local/2/DynamoDBLocal.jar', '-port', '47503', '-dbPath', '/tmp/localstack/state/dynamodb']
`

### Information
Chip: M4 Pro
MacOS: 15.2 
LocalStack: 4.0.4.dev90
Terraform-local:  v1.10.0
Provider: registry.terraform.io/hashicorp/aws v4.67.0

**Comment by alexrashed** [comment]
@johnfercher I think you issue is not related to this issue, but is tackled in https://github.com/localstack/localstack/issues/12054, could that be?

**Comment by johnfercher** [comment]
Yes, is the same issue. Sorry, didn't find that.
