### ISSUE TITLE
bug: localstack start on version 0.13.x terminates early on windows and doesnt start any containers

### ISSUE THREAD

**Issue by rwdalpe** [localstack/localstack#5173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I install localstack 0.13.x via pip on Windows, I cannot start the application via `localstack start`. The command terminates early and does not show any output or start any containers.

Everything works fine if I install a 0.12.x version of localstack explicitly.

```
pip install localstack==0.12.20 localstack-ext==0.12.20
```

### Expected Behavior

`localstack start` starts the containers and displays output like it did for 0.12.x

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Install localstack via pip on windows.

```
pip install localstack
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

Example output:

```
PS C:\Users\wdalpe> localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.1.2

[11:05:09] starting LocalStack in Docker mode 🐳                                                                                                                                       localstack.py:115
2021-12-22T11:05:11.727:INFO:bootstrap.py: Execution of "prepare_host" took 2058.09ms
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
'uname' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\wdalpe>
```

Output of `localstack --debug start`

```
PS C:\Users\wdalpe> localstack --debug start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.1.2

[11:05:39] starting LocalStack in Docker mode 🐳                                                                                                                                       localstack.py:115
2021-12-22T11:05:39.556:DEBUG:stevedore.extension: found extension EntryPoint(name='prepare_host_machine_id', value='localstack.utils.analytics.metadata:prepare_host_machine_id', group='localstack.hooks.prepare_host')
2021-12-22T11:05:39.558:DEBUG:stevedore.extension: found extension EntryPoint(name='activate_pro_key_on_host', value='localstack_ext.plugins:activate_pro_key_on_host', group='localstack.hooks.prepare_host')
2021-12-22T11:05:39.558:DEBUG:localstack.utils.docker_utils: Running container with image: localstack/localstack
2021-12-22T11:05:39.558:DEBUG:localstack.utils.docker_utils: Creating container with image localstack/localstack, command '['bash', '-c', 'ping -c 1 host.docker.internal']', entrypoint '', volumes None, env vars None
2021-12-22T11:05:40.357:DEBUG:localstack.utils.docker_utils: Starting container 69d509b0cea4a370bda5f524c931f619267504558d9d8c4c05008b17a541205f
2021-12-22T11:05:40.971:DEBUG:localstack.utils.docker_utils: Removing container: 69d509b0cea4a370bda5f524c931f619267504558d9d8c4c05008b17a541205f
2021-12-22T11:05:41.690:DEBUG:stevedore.extension: found extension EntryPoint(name='create_dns_forward', value='localstack_ext.plugins:create_dns_forward', group='localstack.hooks.prepare_host')
2021-12-22T11:05:41.690:DEBUG:stevedore.extension: found extension EntryPoint(name='start_ec2_container', value='localstack_ext.plugins:start_ec2_daemon', group='localstack.hooks.prepare_host')
2021-12-22T11:05:41.701:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.prepare_host_machine_id = <function prepare_host_machine_id at 0x0000021A8038EAF0>)
2021-12-22T11:05:41.711:DEBUG:plugin.manager: loading plugin localstack.hooks.prepare_host:prepare_host_machine_id
2021-12-22T11:05:41.711:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.activate_pro_key_on_host = <function activate_pro_key_on_host at 0x0000021A80428E50>)
2021-12-22T11:05:41.731:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:activate_pro_key_on_host is disabled
2021-12-22T11:05:41.752:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.create_dns_forward = <function create_dns_forward at 0x0000021A80428F70>)
2021-12-22T11:05:41.772:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:create_dns_forward is disabled
2021-12-22T11:05:41.772:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.start_ec2_daemon = <function start_ec2_daemon at 0x0000021A804430D0>)
2021-12-22T11:05:41.793:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:start_ec2_daemon is disabled
2021-12-22T11:05:41.803:INFO:bootstrap.py: Execution of "prepare_host" took 2246.50ms
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
2021-12-22T11:05:41.823:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2021-12-22T11:05:41.851:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_edge_port', value='localstack.plugins:configure_edge_port', group='localstack.hooks.configure_localstack_container')
2021-12-22T11:05:41.854:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_pro_container', value='localstack_ext.plugins:configure_pro_container', group='localstack.hooks.configure_localstack_container')
2021-12-22T11:05:41.861:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_edge_port = <function configure_edge_port at 0x0000021A804438B0>)
2021-12-22T11:05:41.861:DEBUG:plugin.manager: loading plugin localstack.hooks.configure_localstack_container:configure_edge_port
2021-12-22T11:05:41.863:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_pro_container = <function configure_pro_container at 0x0000021A804431F0>)
2021-12-22T11:05:41.865:DEBUG:plugin.manager: plugin localstack.hooks.configure_localstack_container:configure_pro_container is disabled
2021-12-22T11:05:41.865:DEBUG:localstack.plugins: configuring container with edge ports: [4566, 0]
2021-12-22T11:05:41.880:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2021-12-22T11:05:41.904:DEBUG:localstack.utils.docker_utils: Run container with cmd: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'DEBUG=1', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
2021-12-22T11:05:41.905:DEBUG:localstack.utils.run: Executing command: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'DEBUG=1', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
'uname' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\wdalpe>
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.1.2
- Python: seen on 3.9.6 and 3.8.10
```

### Anything else?

As mentioned, installing localstack 0.12.x via pip functions as expected.

```
pip install localstack==0.12.20 localstack-ext==0.12.20
```
```
PS C:\Users\wdalpe> localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.12.20

[11:11:02] starting LocalStack in Docker mode 🐳                                                                                                                                       localstack.py:106
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
['docker', 'run', '-it', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '--rm', '--privileged', '--name', 'localstack_main', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:/tmp/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', 'localstack/localstack']
'uname' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
Waiting for all LocalStack services to be ready
2021-12-22 19:11:04,365 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-12-22 19:11:04,367 INFO supervisord started with pid 15
2021-12-22 19:11:05,372 INFO spawned: 'infra' with pid 21
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner

LocalStack version: 0.13.1
LocalStack Docker container id: 0d2a2888d4a2
LocalStack build date: 2021-12-20
LocalStack build git hash: 53a41147

2021-12-22 19:11:06,494 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting edge router (https port 4566)...
Ready.
[2021-12-22 19:11:06 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-12-22T19:11:06.629:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
```

**Comment by dfangl** [comment]
Seems possibly fixed by #5151 . Should be fixed then with the next release of the pip package!

**Comment by rwdalpe** [comment]
Is #5151 a part of 0.13.2? If so, unfortunately I don't think it fixed it. I don't see those `uname` errors anymore, but it still terminates with no further output.

```
PS ~> localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.2

[10:01:46] starting LocalStack in Docker mode 🐳                                                                                                                                       localstack.py:115
2021-12-23T10:01:47.824:INFO:bootstrap.py: Execution of "prepare_host" took 1257.27ms
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
PS ~>
```

```
PS ~> localstack --debug start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.2

[10:01:35] starting LocalStack in Docker mode 🐳                                                                                                                                       localstack.py:115
2021-12-23T10:01:35.155:DEBUG:stevedore.extension: found extension EntryPoint(name='prepare_host_machine_id', value='localstack.utils.analytics.metadata:prepare_host_machine_id', group='localstack.hooks.prepare_host')
2021-12-23T10:01:35.161:DEBUG:stevedore.extension: found extension EntryPoint(name='activate_pro_key_on_host', value='localstack_ext.plugins:activate_pro_key_on_host', group='localstack.hooks.prepare_host')
2021-12-23T10:01:35.163:DEBUG:localstack.utils.docker_utils: Running container with image: localstack/localstack
2021-12-23T10:01:35.165:DEBUG:localstack.utils.docker_utils: Creating container with image localstack/localstack, command '['bash', '-c', 'ping -c 1 host.docker.internal']', entrypoint '', volumes None, env vars None
2021-12-23T10:01:35.277:DEBUG:localstack.utils.docker_utils: Starting container 9c17b97202cc03b6197b8e7d1f259959234d20ed6972582c6699f4af15681780
2021-12-23T10:01:35.880:DEBUG:localstack.utils.docker_utils: Removing container: 9c17b97202cc03b6197b8e7d1f259959234d20ed6972582c6699f4af15681780
2021-12-23T10:01:36.423:DEBUG:stevedore.extension: found extension EntryPoint(name='create_dns_forward', value='localstack_ext.plugins:create_dns_forward', group='localstack.hooks.prepare_host')
2021-12-23T10:01:36.423:DEBUG:stevedore.extension: found extension EntryPoint(name='start_ec2_container', value='localstack_ext.plugins:start_ec2_daemon', group='localstack.hooks.prepare_host')
2021-12-23T10:01:36.424:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.prepare_host_machine_id = <function prepare_host_machine_id at 0x000001FD6A33DEE0>)
2021-12-23T10:01:36.424:DEBUG:plugin.manager: loading plugin localstack.hooks.prepare_host:prepare_host_machine_id
2021-12-23T10:01:36.425:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.activate_pro_key_on_host = <function activate_pro_key_on_host at 0x000001FD6A3DF4C0>)
2021-12-23T10:01:36.425:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:activate_pro_key_on_host is disabled
2021-12-23T10:01:36.425:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.create_dns_forward = <function create_dns_forward at 0x000001FD6A3DF5E0>)
2021-12-23T10:01:36.425:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:create_dns_forward is disabled
2021-12-23T10:01:36.426:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.start_ec2_daemon = <function start_ec2_daemon at 0x000001FD6A3DF700>)
2021-12-23T10:01:36.426:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:start_ec2_daemon is disabled
2021-12-23T10:01:36.426:INFO:bootstrap.py: Execution of "prepare_host" took 1271.62ms
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
2021-12-23T10:01:36.431:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2021-12-23T10:01:36.439:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_edge_port', value='localstack.plugins:configure_edge_port', group='localstack.hooks.configure_localstack_container')
2021-12-23T10:01:36.444:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_pro_container', value='localstack_ext.plugins:configure_pro_container', group='localstack.hooks.configure_localstack_container')
2021-12-23T10:01:36.455:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_edge_port = <function configure_edge_port at 0x000001FD6A3DFEE0>)
2021-12-23T10:01:36.455:DEBUG:plugin.manager: loading plugin localstack.hooks.configure_localstack_container:configure_edge_port
2021-12-23T10:01:36.456:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_pro_container = <function configure_pro_container at 0x000001FD6A3DF820>)
2021-12-23T10:01:36.456:DEBUG:plugin.manager: plugin localstack.hooks.configure_localstack_container:configure_pro_container is disabled
2021-12-23T10:01:36.457:DEBUG:localstack.plugins: configuring container with edge ports: [4566, 0]
2021-12-23T10:01:36.461:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2021-12-23T10:01:36.471:DEBUG:localstack.utils.docker_utils: Run container with cmd: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
2021-12-23T10:01:36.476:DEBUG:localstack.utils.run: Executing command: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
PS ~>
```

**Comment by mmcclelland1002** [comment]
Any update on this? I'm having the same issue with docker compose

**Comment by rwdalpe** [comment]
Just noting that this is still happening in 0.13.2.1 as well.

```
PS ~> localstack --debug start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.2.1

[09:23:04] starting LocalStack in Docker mode 🐳                                                      localstack.py:115
2022-01-03T09:23:04.581:DEBUG:stevedore.extension: found extension EntryPoint(name='prepare_host_machine_id', value='localstack.utils.analytics.metadata:prepare_host_machine_id', group='localstack.hooks.prepare_host')
2022-01-03T09:23:04.589:DEBUG:stevedore.extension: found extension EntryPoint(name='activate_pro_key_on_host', value='localstack_ext.plugins:activate_pro_key_on_host', group='localstack.hooks.prepare_host')
2022-01-03T09:23:04.591:DEBUG:localstack.utils.docker_utils: Running container with image: localstack/localstack
2022-01-03T09:23:04.592:DEBUG:localstack.utils.docker_utils: Creating container with image localstack/localstack, command '['bash', '-c', 'ping -c 1 host.docker.internal']', entrypoint '', volumes None, env vars None
2022-01-03T09:23:05.215:DEBUG:localstack.utils.docker_utils: Starting container 42465c8858c3b8d5eff13eb29f6eb00aec07e6fbe8b170a367a129ff3ff9c745
2022-01-03T09:23:06.639:DEBUG:localstack.utils.docker_utils: Removing container: 42465c8858c3b8d5eff13eb29f6eb00aec07e6fbe8b170a367a129ff3ff9c745
2022-01-03T09:23:07.159:DEBUG:stevedore.extension: found extension EntryPoint(name='create_dns_forward', value='localstack_ext.plugins:create_dns_forward', group='localstack.hooks.prepare_host')
2022-01-03T09:23:07.177:DEBUG:stevedore.extension: found extension EntryPoint(name='start_ec2_container', value='localstack_ext.plugins:start_ec2_daemon', group='localstack.hooks.prepare_host')
2022-01-03T09:23:07.178:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.prepare_host_machine_id = <function prepare_host_machine_id at 0x000001ECDA5E0EE0>)
2022-01-03T09:23:07.179:DEBUG:plugin.manager: loading plugin localstack.hooks.prepare_host:prepare_host_machine_id
2022-01-03T09:23:07.180:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.activate_pro_key_on_host = <function activate_pro_key_on_host at 0x000001ECDA684430>)
2022-01-03T09:23:07.180:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:activate_pro_key_on_host is disabled
2022-01-03T09:23:07.181:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.create_dns_forward = <function create_dns_forward at 0x000001ECDA684550>)
2022-01-03T09:23:07.181:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:create_dns_forward is disabled
2022-01-03T09:23:07.181:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.start_ec2_daemon = <function start_ec2_daemon at 0x000001ECDA684670>)
2022-01-03T09:23:07.181:DEBUG:plugin.manager: plugin localstack.hooks.prepare_host:start_ec2_daemon is disabled
2022-01-03T09:23:07.187:INFO:bootstrap.py: Execution of "prepare_host" took 2605.58ms
──────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────
2022-01-03T09:23:07.193:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2022-01-03T09:23:07.210:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_edge_port', value='localstack.plugins:configure_edge_port', group='localstack.hooks.configure_localstack_container')
2022-01-03T09:23:07.214:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_pro_container', value='localstack_ext.plugins:configure_pro_container', group='localstack.hooks.configure_localstack_container')
2022-01-03T09:23:07.215:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_edge_port = <function configure_edge_port at 0x000001ECDA684E50>)
2022-01-03T09:23:07.216:DEBUG:plugin.manager: loading plugin localstack.hooks.configure_localstack_container:configure_edge_port
2022-01-03T09:23:07.216:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_pro_container = <function configure_pro_container at 0x000001ECDA684790>)
2022-01-03T09:23:07.217:DEBUG:plugin.manager: plugin localstack.hooks.configure_localstack_container:configure_pro_container is disabled
2022-01-03T09:23:07.217:DEBUG:localstack.plugins: configuring container with edge ports: [4566, 0]
2022-01-03T09:23:07.221:DEBUG:localstack.utils.docker_utils: Listing containers with filters: None
2022-01-03T09:23:07.231:DEBUG:localstack.utils.docker_utils: Run container with cmd: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
2022-01-03T09:23:07.237:DEBUG:localstack.utils.run: Executing command: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-v', 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:12121:12121', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
PS ~>
```

**Comment by rwdalpe** [comment]
I tried running that `docker run` command that the debug output ends on as a standalone command, and I got an error that might shed light on what's happening:

```
docker run --rm --name localstack_main -v 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack:C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack' -v 'C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack\\cache:/var/lib/localstack/cache' -v '/var/run/docker.sock:/var/run/docker.sock' -p 127.0.0.1:4566:4566 -p 127.0.0.1:4571:4571 -p 127.0.0.1:12121:12121 -e TEST_AWS_ACCOUNT_ID=000000000000 -e LOCALSTACK_HOSTNAME=localhost -e DEFAULT_REGION=us-east-1 -e DEBUG=1 -e 'DOCKER_HOST=unix:///var/run/docker.sock' -e 'HOST_TMP_FOLDER=C:\\Users\\wdalpe\\AppData\\Local\\Temp\\localstack' -e SET_TERM_HANDLER=1 --privileged localstack/localstack
docker: Error response from daemon: invalid mode: \\Users\\wdalpe\\AppData\\Local\\Temp\\localstack.
See 'docker run --help'.
```

Looks like that first volume definition has a windows path on the right side of the declaration? I'm not familiar with how localstack expects to set up its tmp volume, but based on the other volume definitions it doesn't seem to match.

**Comment by rwdalpe** [comment]
Seems like in 0.12.20 the tmp folder was hardcoded to `/tmp/localstack`: https://github.com/localstack/localstack/blob/v0.12.20/localstack/utils/bootstrap.py#L595

Now in 0.13.x the volume target is the same value as `config.TMP_FOLDER`, which is a windows path in this case.

**Comment by dfangl** [comment]
Hi! You are right, there definitively is an issue here. Will discuss and implement a fix soon!

**Comment by dfangl** [comment]
Hi there @rwdalpe @mmcclelland1002 !
This issue should now be fixed in the latest pip release. Please try running `pip install -U localstack` to upgrade and check it out!
Thanks for reporting this, sorry about the long turnaround!

**Comment by rwdalpe** [comment]
@dfangl things are looking good to me after the latest update! `localstack start` is starting the containers and I'm not seeing any error output. Thanks again for your work on this!
