### ISSUE TITLE
bug: CloudFormation/CDK AppSync Resolvers are not updated

### ISSUE THREAD

**Issue by thantos** [localstack/localstack#5987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying Appsync resolvers to `localstack` via CloudFormation/CDK, update and deletes to resolver response templates (AWS::AppSync::Resolver) are not reflected.

Creating a new resolver/field resource with a new name does show up on deployment. Old resolvers are not deleted.

This error is shown with DEBUG on (deployment succeeds)

```
2022-05-02T19:53:50.760:WARNING:localstack.utils.cloudformation.template_deployer: Action delete for resource type AppSync::Resolver not available. To find out if AppSync::Resolver is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
```

Which is strange because the resolver was created, but cannot be deleted or updated?

`AWS::AppSync::Resolver` is in the list of resources supported by Pro.

### Expected Behavior

CloudFormation templates should be reflected, including updates or deletes of `AppSync::Resolver`.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Deployment via CDK Deployments and CDK Local

Original Resource:

```json
        "graphql1Queryhi3ResolverED1FF83E": {
          "Type": "AWS::AppSync::Resolver",
          "Properties": {
            "ApiId": {
              "Fn::GetAtt": [
                "graphql1F453A15C",
                "ApiId"
              ]
            },
            "FieldName": "hi3",
            "TypeName": "Query",
            "DataSourceName": "None",
            "Kind": "UNIT",
            "RequestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "ResponseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi'))\n$v1"
          },
          "DependsOn": [
            "graphql1NoneCDCC4757",
            "graphql1Schema94C4E4ED"
          ]
        }
```

Updated Resource (notice the change to the response mapping template):

```json
        "graphql1Queryhi3ResolverED1FF83E": {
          "Type": "AWS::AppSync::Resolver",
          "Properties": {
            "ApiId": {
              "Fn::GetAtt": [
                "graphql1F453A15C",
                "ApiId"
              ]
            },
            "FieldName": "hi3",
            "TypeName": "Query",
            "DataSourceName": "None",
            "Kind": "UNIT",
            "RequestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "ResponseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi2'))\n#return($v1)"
          },
          "DependsOn": [
            "graphql1NoneCDCC4757",
            "graphql1Schema94C4E4ED"
          ]
        }
```

Resolve of the `list-resolvers` operation

   awslocal appsync list-resolvers --api-id 5b73d474 --type-name Query

```json
        {
            "fieldName": "hi3",
            "dataSourceName": "None",
            "resolverArn": "arn:aws:appsync:us-east-1:000000000000:apis/5b73d474/types/Query/resolvers/hi3",
            "requestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "responseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi'))\n$v1",
            "kind": "UNIT"
        }
```

Issues:
1. hi3 was not updated

Result after renaming the field to "hi4". 

      awslocal appsync list-resolvers --api-id 5b73d474 --type-name Query

Issues:
1. hi3 no longer exists in the template, only 4 does

```json
        {
            "fieldName": "hi3",
            "dataSourceName": "None",
            "resolverArn": "arn:aws:appsync:us-east-1:000000000000:apis/5b73d474/types/Query/resolvers/hi3",
            "requestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "responseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi'))\n$v1",
            "kind": "UNIT"
        },
        {
            "fieldName": "hi4",
            "dataSourceName": "None",
            "resolverArn": "arn:aws:appsync:us-east-1:000000000000:apis/5b73d474/types/Query/resolvers/hi4",
            "requestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "responseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi2'))\n#return($v1)",
            "kind": "UNIT"
        }
```

### Environment

```markdown
- OS: Ubuntu/WSL2
- LocalStack: 0.14.2.1
```

**Comment by thantos** [comment]
After more testing, I am not sure Create works completely either.

```json
        {
            "fieldName": "hi5",
            "dataSourceName": "None",
            "resolverArn": "arn:aws:appsync:us-east-1:000000000000:apis/5b73d474/types/Query/resolvers/hi5",
            "requestMappingTemplate": "{\n    \"version\": \"2018-05-29\",\n    \"payload\": null\n  }",
            "responseMappingTemplate": "#set($v1 = {})\n$util.qr($v1.put('value', 'hi2'))\n$util.toJson($v1)",
            "kind": "UNIT"
        }
```

Calling the API `Query { hi5 }` return `{ hi5: { value: null } }`

While the same resource on AWS returns

```json
{
  "data": {
    "hi5": {
      "value": "hi"
    }
  }
}
```

**Comment by whummer** [comment]
Hi @thantos, quick update - we've pushed a couple more enhancements which should (hopefully) get some of the issues you've mentioned resolved. Can you please pull the `latest` Docker image and give it another try? Thanks!

**Comment by thantos** [comment]
```
2022-05-15T08:40:00.701:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type AppSync::ApiKey when resolving references of resource graphql1DefaultApiKeyDFD3D483: {"Type": "AWS::AppSync::ApiKey", "DependsOn": ["graphql1Schema94C4E4ED"], "LogicalResourceId": "graphql1DefaultApiKeyDFD3D483", "Properties": {"ApiId": {"Fn::GetAtt": ["graphql1F453A15C", "ApiId"]}}}. To find out if AppSync::ApiKey is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
```

`AWS::AppSync::ApiKey` is listed in the "supported" docs.

**Comment by thantos** [comment]
Trying with IAM instead

> 2022-05-15T08:50:29.070:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type AppSync::GraphQLApi when resolving references of resource graphql1F453A15C: {"Type": "AWS::AppSync::GraphQLApi", "LogicalResourceId": "graphql1F453A15C", "Properties": {"AuthenticationType": "AWS_IAM", "Name": "Api"}, "PhysicalResourceId": null}. To find out if AppSync::GraphQLApi is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation

**Comment by whummer** [comment]
Thanks for the update @thantos . These CloudFormation resources should definitely be supported - can you please double-check if your API key is configured properly? (You should find a message like `Successfully activated API key` in the startup logs). If something is not working with your key, can you please get in touch with us via email or Slack directly, so we can get it resolved.. Thanks

**Comment by thantos** [comment]
API Key was indeed the problem. ✅ 

To be clear, this is still an issue, resolvers are not updated.

**Comment by whummer** [comment]
Hi @thantos , quick update: we've pushed another set of changes, can you please verify one more time with the `latest` Docker image - the resolvers should now be (hopefully) properly deleted/updated by changes in your CloudFormation template.. Thanks
