### ISSUE TITLE
bug: RDS instance not accessible after restart and call to RDS service (Pro version, Persistence enabled)

### ISSUE THREAD

**Issue by sorendaugaard** [localstack/localstack#6550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running 1.0.1 in the Pro version with `PERSISTENCE` enabled via docker compose.

When I boot up my empty container and provision an PG database I can connect to the database and run queries. However after restarting the localstack container I can no longer connect to the database.

I’ve tried to “awake” up the service using a `awslocal rds describe-db-instances` and it shows the instance in the `available` state and on the expected port and host, but I am still not able to connect to it.

I have tried to connect to it from outside the docker container and from a lambda inside the docker container and both work when its first initialized but do **not** work after a restart.

### Expected Behavior

I would expect the RDS instance to come up and be accessible after a restart (or at least after a restart and a call to the RDS service to put it into the running state). 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose.yml`
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.0
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - PERSISTENCE=1
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Started with `docker compose up`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
# Create database
$ awslocal rds create-db-instance --db-name test --db-instance-identifier test-db --engine postgres --
master-username test --master-user-password test --db-instance-class db.t3.micro

# psql to db - success!
$ psql -d test -U test -p 4510 -h localhost -W
Password:
psql (14.4, server 11.16 (Debian 11.16-0+deb10u1))
Type "help" for help.

# restart docker 
docker compose restart

# psql to db - doesn't work :( maybe that makes sense because the RDS service is not running yet? 
$ psql -d test -U test -p 4510 -h localhost -W
Password:
psql: error: connection to server at "localhost" (::1), port 4510 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

# check RDS is running (its not)
$ curl localhost:4566/health | jq | grep running 

# describe RDS instances
$ awslocal rds describe-db-instances
{
    "DBInstances": [
        {
            "DBInstanceIdentifier": "test-db",
            "DBInstanceClass": "db.t3.micro",
            "Engine": "postgres",
            "DBInstanceStatus": "available",
            "MasterUsername": "test",
            "DBName": "test",
            "Endpoint": {
                "Address": "localhost",
                "Port": 4510
            },
..... 

# check RDS is running - it is! 
$ url localhost:4566/health | jq | grep running
    "rds": "running",

# psql to db - at this point we would expect it to be available because we just described it and it was said to be available ... 
$ psql -d test -U test -p 4510 -h localhost -W
Password:
psql: error: connection to server at "localhost" (::1), port 4510 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections? 
```

### Environment

```markdown
- OS: MacOS
- LocalStack: 1.0.1
```

**Comment by bentsku** [comment]
Hello @sorendaugaard and thank you for your detailed report!
The issue should be fixed and part of the latest release. Could you please try to run `docker pull localstack/localstack:latest` and give it a run?
Thanks a lot!

**Comment by amitassaraf** [comment]
FYI This is still happening to us in the latest image

**Comment by jaimelamacollado** [comment]
I am getting the same error on     image: localstack/localstack-pro

**Comment by circulon** [comment]
> I am getting the same error on image: localstack/localstack-pro

Same here.
just pulled latest pro image and both elasticache (redis) and rds (pgsql cluster) fail to be avail on 
`docker-compose up -d` 
also have set `EAGER_SERVICE_LOADING=1` which does not fix the issue

**Comment by trdyer** [comment]
I have this issue and added a healthcheck to my compose files that use awslocal to call the services I want running in order to start them up.

ie

``` 
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal rds describe-db-instances && awslocal kms list-keys && aws secretsmanager list-secrets
      interval: 10s
      timeout: 15s
      start_period: 20s
      retries: 5
```

**Comment by bentsku** [comment]
Hello @circulon! The original issue as described by the user has been fixed: after restarting LocalStack and loading the `rds` service, the instances would not come up at all.

The issue you're describing is different: services in LocalStack are lazy-loaded.
In the steps you're describing, when you restart LocalStack, RDS is not loaded yet: calling `awslocal rds <operation>` will load the service. With persistence enabled, this will recreate your RDS instances, which takes some time, and then they are available again. You'd need to check the status of those instances like you would do at creation time in order to be sure they are available. 

You could however load the service at startup by using [Initialization Hooks](https://docs.localstack.cloud/references/init-hooks/), so with a small script you could do the `awslocal` call.
