### ISSUE TITLE
bug: Creating an S3 bucket via terraform with dots in the name fails

### ISSUE THREAD

**Issue by OxonianCambion** [localstack/localstack#6687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that there is some sort of issue with "." in s3 bucket filenames created via terraform:
"." is a valid character according to the [naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)

If I attempt to use the following file in terraform (via `tflocal`):

```
resource "aws_s3_bucket" "test-bucket" {
  bucket = "my.bucket"
}
```
the cli stalls trying to create:
```
aws_s3_bucket.developer_area_bucket: Creating...
aws_s3_bucket.developer_area_bucket: Still creating... [10s elapsed]
aws_s3_bucket.developer_area_bucket: Still creating... [20s elapsed]
... etc
```

with the console of the localstack instance giving:
```
2022-08-17T10:21:35.833 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
2022-08-17T10:21:35.835  INFO --- [   asgi_gw_0] localstack.request.http    : PUT / => 500
2022-08-17T10:21:36.002 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
2022-08-17T10:21:36.003  INFO --- [   asgi_gw_1] localstack.request.http    : PUT / => 500
```

Note that using `awslocal` gives the correct behaviour:
```
$ awslocal s3api create-bucket --bucket my.bucket
{
    "Location": "/my.bucket"
}
```

### Expected Behavior

Terraform should be able to create the bucket `my.bucket` in the localstack instance.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    tflocal init
    tflocal apply

#### Relevant file
```
resource "aws_s3_bucket" "test-bucket" {
  bucket = "my.bucket"
}
```

### Environment

```markdown
- OS: WSL2 + Ubuntu 20.04
- LocalStack: 1.0.4
```

**Comment by thrau** [comment]
Hi Gregory @OxonianCambion , thanks for reporting. I can't reproduce the issue on my machine. Could you run localstack with `LS_LOG=trace` and post the log output after running terraform apply?

Also, can you confirm that this also occurs after removing the terraform state files? `rm -rf .terraform* terraform.tfstate`. Thanks!

**Comment by OxonianCambion** [comment]
Hi Thomas; thanks for your interest!

I've run it without cleaning and with cleaning. I've quickly diffed the outputs and there doesn't seem to be any difference

The key error appears to be here:
```
2022-08-18T09:14:06.817 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : PUT my.bucket.s3.localhost.localstack.cloud:4566/
2022-08-18T09:14:06.827 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/protocol/op_router.py", line 287, in match
rule, args = matcher.match(get_raw_path(request), method=method, return_rule=True)
File "/opt/code/localstack/.venv/lib/python3
.10/site-packages/werkzeug/routing.py", line 2042, in match
raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 552, in parse
operation, uri_params = self._operation_router.match(request)
File "/opt/code/localstack/localstack/aws/protocol/op_router.py", line 291, in match
raise NotFound() from e
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

Here is the output:
First just rerunning - my console commands/output:
[tfl_local_without_cleaning.txt](https://github.com/localstack/localstack/files/9372272/tfl_local_without_cleaning.txt)
and the localstack logs.
[ls_log_without_cleaning.txt](https://github.com/localstack/localstack/files/9372273/ls_log_without_cleaning.txt)

I terminated both, cleaned the tf files and re-ran both:
[ls_log_with_cleaning.txt](https://github.com/localstack/localstack/files/9372269/ls_log_with_cleaning.txt)
[tfl_local_with_cleaning.txt](https://github.com/localstack/localstack/files/9372270/tfl_local_with_cleaning.txt)

**Comment by whummer** [comment]
Hi @OxonianCambion, this seems to be related to how `tflocal` is handling local endpoints - by default it is using **hostname-based addressing** for S3 buckets (using `http://<bucket_name>.s3.localhost.localstack.cloud:4566` as the target API endpoint), whereas for bucket names containing dots we need to be using **path-based addressing** (which is the default when `http://localhost:4566` as the endpoint URL).

We have pushed a small fix - can you please upgrade to the latest version of `tflocal`:
```
pip install --upgrade 'terraform-local>=0.4'
```

... and then try deploying your TF sample like this:
```
S3_HOSTNAME=localhost tflocal apply
```

Hope that helps - please let us know.. We'll look into adding a patch for `tflocal` for not having to specify `S3_HOSTNAME=localhost` if your sample contains bucket names with dots. Thanks!

**Comment by OxonianCambion** [comment]
Hi @whummer 
Yes - that seems to have worked!

I've attached the logs, but the key parts of my command line interactions are here:
```
$ rm -rf .terraform* terraform.tfstate
$ pip show terraform-local
Name: terraform-local
Version: 0.4
Summary: Thin wrapper script to run Terraform against LocalStack
Home-page: https://github.com/localstack/terraform-local
Author: LocalStack Team
Author-email: info@localstack.cloud
License: Apache License 2.0
Location: /home/gremos/.pyenv/versions/3.9.13/lib/python3.9/site-packages
Requires: localstack-client
Required-by:

$ tflocal init
...

$ S3_HOSTNAME=localhost tflocal apply
...
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_s3_bucket.test-bucket: Creating...
aws_s3_bucket.test-bucket: Creation complete after 0s [id=my.bucket]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ awslocal s3 ls
2022-08-30 12:51:41 my.bucket
$

```

[ls_log_new.txt](https://github.com/localstack/localstack/files/9452578/ls_log_new.txt)
[tfl_local_new.txt](https://github.com/localstack/localstack/files/9452579/tfl_local_new.txt)

I did check without setting `S3_HOSTNAME` and unsurprisingly it still fails.

Thanks! (I'll let you guys do any housekeeping and close the issue.)

Greg

**Comment by Dowwie** [comment]
It's December 2022 and this issue persists with the latest versions of localstack and tflocal from pip package repo:

**Comment by bentsku** [comment]
Hello @Dowwie and thanks for your report. 

We have been working on a new implementation of S3, and it is now available under a feature flag. Could you try setting `“PROVIDER_OVERRIDE_S3=“asf”` and see if that would fix your problem? It seems we have a test that would cover this issue and it looks like it's fixed with the new implementation. 

In the case it's not, don't hesitate to provide us any logs where the exception can be seen. Thanks a lot for your feedback! 

_Note: if you are a Pro user, you should use the flag “asf_pro” instead of “asf”._

**Comment by Dowwie** [comment]
I tried `“PROVIDER_OVERRIDE_S3=“asf” tflocal apply` and it did not address the problem, returning  `localstack.request.http    : PUT / => 500`

**Comment by bentsku** [comment]
Oh sorry, I did not precise that this needs to be used in LocalStack. You would need to set this environment variable when you start LocalStack, either via the CLI or the docker-compose. See https://docs.localstack.cloud/references/configuration/

In any case, if you still encounter an error, could you please set `DEBUG=1` and `LS_LOG=trace` before starting LocalStack so we could have a bit more informations about what is going on. Thanks!

**Comment by bentsku** [comment]
I am unable to reproduce the issue with the setting `PROVIDER_OVERRIDE_S3="asf"`.

Using this Terraform sample given:
```
resource "aws_s3_bucket" "test-bucket" {
  bucket = "my.bucket"
}
```

I can successfully create and deploy the bucket using
```bash
$ tflocal init
$ tflocal apply
> aws_s3_bucket.test-bucket: Creating...
> aws_s3_bucket.test-bucket: Creation complete after 1s [id=my.bucket]

$ awslocal s3api list-buckets
> {
    "Buckets": [
        {
            "Name": "my.bucket",
            "CreationDate": "2022-12-13T16:32:29Z"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
   }
}

```
Could you provide us some logs with those settings in LocalStack: `DEBUG=1` and `LS_LOG=trace` ?

**Comment by daringordon** [comment]
It seems that the use of double quotes for the string value is what caused the issue.  The following env var worked: 
 `PROVIDER_OVERRIDE_S3=asf`

Have you got an idea as to what version of localstack will include this fix and allow me to remove the env var?  I'd like to know what to track.  Thanks for your quick response on this matter, too.

**Comment by bentsku** [comment]
Oh, sorry for inducing you in error, my bad. I will pay attention next time! 

Yes, the new S3 implementation will be the default for the next major release, 2.0. This should come end of next quarter. In the meantime, most of our next S3 fixes and new features will be done in this new implementation, and it passes our full test suite. It is stable and safe to use this env var until then. Thanks a lot for your quick feedback, and I'm glad the issue is solved!

I'll close the issue now it seems to be solved!
