### ISSUE TITLE
bug: concurrent requests made to a `FIFO` queue return messages from the same `MessageGroupId`

### ISSUE THREAD

**Issue by tomazfernandes** [localstack/localstack#6766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When concurrent requests are made to a `FIFO` queue, requests return messages from the same `MessageGroupId`.

#### Scenario Example

Consider we have a FIFO queue with 10 messages from the same `MessageGroupId`.

Then we make two concurrent `receiveMessage` requests for `5 messages` each.

According to `SQS FIFO` contract, we should receive only 5 messages in the first request, and none on the second request, as long as `Visibility Timeout` is not expired.

With `LocalStack 1.0.4` wrongly we receive all 10 messages, 5 in each request.

When the same is done targeting `AWS`, the behavior is correct, the first request returns 5 messages and the second one no messages.

### Expected Behavior

We should not receive messages from the same `MessageGroupId` for concurrent requests to `FIFO` queues.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With `TestContainers`
```java
private static final String LOCAL_STACK_VERSION = "localstack/localstack:1.0.4";

static LocalStackContainer localstack = new LocalStackContainer(DockerImageName.parse(LOCAL_STACK_VERSION))
	.withServices(SQS).withReuse(true);
```

I've tried with `reuse(false)` and the behavior is unchanged.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I created a `JUnit5` test that executes the steps I've described in the previous section and that reproduces the behavior. When targeting `AWS` the test passes, when targeting `LocalStack` it doesn't. All results are consistent throughout many test runs.

```java

@Test
void receivesTwoBatchesFromSameMessageGroup() {
	String messageGroupId = UUID.randomUUID().toString();
	String queueName = "my-fifo-queue.fifo";
	logger.info("Create queue {}", queueName);
	String queueUrl = sqsAsyncClient.createQueue(CreateQueueRequest.builder()
			.queueName(queueName)
			.attributes(Collections.singletonMap(QueueAttributeName.FIFO_QUEUE, "true"))
			.build())
		.join()
		.queueUrl();
	logger.info("Send 10 messages to url {} for message group {}", queueUrl, messageGroupId);
	List<SendMessageBatchRequestEntry> entries = IntStream.range(0, 10)
		.mapToObj(index -> SendMessageBatchRequestEntry
			.builder()
			.messageGroupId(messageGroupId)
			.messageBody("test - " + index)
			.messageDeduplicationId(UUID.randomUUID().toString())
			.id(UUID.randomUUID().toString())
			.build())
		.collect(toList());
	sqsAsyncClient.sendMessageBatch(SendMessageBatchRequest
		.builder()
			.entries(entries)
		.queueUrl(queueUrl)
		.build())
		.join();
	logger.info("Receive two batches of 5 messages from queue {}", queueUrl);
	CompletableFuture<ReceiveMessageResponse> receiveMessageFuture1 = sqsAsyncClient.receiveMessage(ReceiveMessageRequest
		.builder()
		.queueUrl(queueUrl)
		.attributeNames(QueueAttributeName.ALL)
		.waitTimeSeconds(10)
		.receiveRequestAttemptId(UUID.randomUUID().toString())
		.maxNumberOfMessages(5)
		.build());
	CompletableFuture<ReceiveMessageResponse> receiveMessageFuture2 = sqsAsyncClient.receiveMessage(ReceiveMessageRequest
		.builder()
		.queueUrl(queueUrl)
		.attributeNames(QueueAttributeName.ALL)
		.receiveRequestAttemptId(UUID.randomUUID().toString())
		.waitTimeSeconds(10)
		.maxNumberOfMessages(5)
		.build());
	CompletableFuture.allOf(receiveMessageFuture1, receiveMessageFuture2).join();
	logger.info("Received two batches from queue {}", queueUrl);
	List<software.amazon.awssdk.services.sqs.model.Message> firstBatch = receiveMessageFuture1.join().messages().stream()
		.filter(message -> message.attributes().get(MessageSystemAttributeName.MESSAGE_GROUP_ID).equals(messageGroupId))
		.collect(toList());
	List<software.amazon.awssdk.services.sqs.model.Message> secondBatch = receiveMessageFuture2.join().messages().stream()
		.filter(message -> message.attributes().get(MessageSystemAttributeName.MESSAGE_GROUP_ID).equals(messageGroupId))
		.collect(toList());
	logger.info("First batch: {} messages Second Batch: {} messages", firstBatch.size(), secondBatch.size());
	List<software.amazon.awssdk.services.sqs.model.Message> allMessages = new ArrayList<>(firstBatch);
	allMessages.addAll(secondBatch);
	// Make sure we're not receiving the same messages
	long distinctCount = allMessages.stream().map(software.amazon.awssdk.services.sqs.model.Message::body).distinct().count();
	assertThat(distinctCount).isEqualTo(5);
	assertThat(allMessages).hasSize(5);

}
```

### Environment

```markdown
- OS: MacOS Monterey 12.5
- LocalStack: 1.0.4
```

### Anything else?

Execution logs targeting LocalStack:

![Screen Shot 2022-08-26 at 19 57 16](https://user-images.githubusercontent.com/76525045/187000819-da30692f-6a13-458f-9071-25f0992ccaba.png)

Execution logs targeting AWS:

![Screen Shot 2022-08-26 at 19 56 12](https://user-images.githubusercontent.com/76525045/187000732-5ae04e89-28aa-47dc-9eb1-fc080e245b69.png)

**Comment by thrau** [comment]
Hi Tomaz @tomazfernandes, thanks for the detailed report! That's a great find. Also excited to see the development in spring-cloud-aws!

The issue, I think, boils down to this passage of the [docs on visibility timeout for FIFO queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html):

>  When you receive a message with a message group ID, no more messages for the same message group ID are returned unless you delete the message or it becomes visible.

In other words, in FIFO queues, all messages within a message group share the same visibility timeout, regardless of whether they have been received or not. 

We simply haven't implemented it that way, and I'm not sure this will be super trivial to implement either. However I can see how this behavior is pretty central to FIFO queues. So I'll give it some thought next week.


My naive approach would be the following. Once a message has been received, we sift through the visible queue and remove all messages from the underlying heap that have the same message group id, and move them into the inflight set. Not sure this is really going to work well given that PriorityQueues aren't really built for this sort of access. Another option would maybe be to also keep an "inflight" list of message group ids, and filter in the lower-level get routine: https://github.com/localstack/localstack/blob/0ef849e8aeb1db5a8b645d852a4534ce8b53db36/localstack/services/sqs/provider.py#L497-L504

Maybe @baermat also has some ideas

**Comment by baermat** [comment]
After giving this some thought, your second solution of an "inflight" list of message group ids sound the most promising and least intrusive to me. My approach would have been to peek the heap, check the message group ids, and continue only if there is no match. There is no explicit function for peeking, apparently heap[0] is supposed to do that. Looks a bit hacky to me, but that's how they describe it in the docs. Assuming that we properly handle putting message group ids in and out of inflight, we could do something like this in an overwritten get function of the fifo-queue:
```
def get(self, block=True, timeout=None, visibility_timeout: int = None) -> SqsMessage:
    with self.mutex:
        # peek the heap
        standard_message: SqsMessage = self.visible[0]
        if standard_message and standard_message.message_group_id not in inflight_group_ids:
            return super().get(self, block, timeout, visibility_timeout)
```
This particular solution however is not good because e.g. it locks the whole get method, among other issues. But you get the general idea.

**Comment by ckatsaras-godaddy** [comment]
@thrau @HarshCasper @tomazfernandes @baermat  any update on this issue? I just ran into this today as well and it seems like a very important piece of functionality. Without it, it makes using FIFO queues very difficult. 
Any help is really appreciated 😄

**Comment by tomazfernandes** [comment]
Hi again! First, thanks for the great work you put in `LocalStack`, it's awesome!

> After giving this some thought, your second solution of an "inflight" list of message group ids sound the most promising and least intrusive to me. My approach would have been to peek the heap, check the message group ids, and continue only if there is no match.

I don't know the implementation, so not sure I can help. If this means that, e.g. if one `messageGroupId` is not visible and the first message belongs to that group, it would block a second message from a different group from being polled, that would remain inconsistent in relation to FIFO rules, right?

Also I think consistency is preferable to performance for tests, so IMHO any tradeoffs needed for that should be ok e.g. if there's a need to do some defensive locking.

**Comment by tomwidmer** [comment]
I think you'll need some more book-keeping in FifoQueue to implement this - something like:
```
deduplication: Dict[str, Dict[str, SqsMessage]]
message_group_id_queues: Dict[str, list[SqsMessage]]
processing_message_group_ids: Set[string]
```

Then in `put`, you check if `processing_message_group_ids` contains the id, if not you add it to the set and immediately add the message to `visible`. If it does, you add the message to `message_group_id_queues` instead, under the group id's list.

In `remove`, you remove the id from `processing_message_group_ids`, and enqueue the first message with the same group from `message_group_id_queues` if there is one (removing from that list and deleting from the dict if the list is now empty).

Would that work? It keeps the `visible` priority queue as it is and the `get` method doesn't change. I might be able to look at a PR (though I'm not a Python dev).

**Comment by vbauchart** [comment]
I created a sample Bash script based on AWS CLI that prove the SQS FIFO message ordrering by producing and consuming message based on their GroupId:

https://github.com/vbauchart/aws-sqs-fifo-demo 

If you run it against real AWS SQS, the messages are ordrered but the Localstack SQS implementation give buggy results.

Hope this helps

**Comment by thrau** [comment]
Hey folks! Just letting you know that we've now implemented the message group IDs behavior properly in #8238, and the changes should be available in the latest image. Sorry for the long wait!

Please give it a whirl. /cc @tomazfernandes @ckatsaras-godaddy @vbauchart @tomwidmer

**Comment by tomwidmer** [comment]
Thanks, that's brilliant! When will this be in a release?

**Comment by felixdo** [comment]
I no longer see this in localstack image 2.3.2, seems to be fixed.

**Comment by tyge68** [comment]
I still see issues with fifo / message group id , and still concurrent requests made. It seems it doesn't really respect the "VisibilityTimeout" and so from time to time end up executing the same message twice in parallel. While this is not happening on a real AWS environment.
