### ISSUE TITLE
bug: terraform aws_acm_certificate data source runs indefinitely

### ISSUE THREAD

**Issue by tiagoposse** [localstack/localstack#8156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to retrieve an ACM certificate using the terraform data source "aws_acm_certificate", the certificate is never read and the call runs indefinitely until cancelled.

### Expected Behavior

The certificate is retrieved and the terraform plan executes.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack-pro:2.0.1 ...

#### Terraform code

The following terraform module is sufficient to reproduce this issue:
```
resource "aws_route53_zone" "this" {
  name = "example.com"
}

module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "4.3.2"

  domain_name         = "*.example.com"
  wait_for_validation = true
  zone_id             = aws_route53_zone.this.zone_id
}

data "aws_acm_certificate" "this" {
  depends_on = [module.acm]

  domain = "*.example.com"
}
```

### Environment

```markdown
- Docker
- LocalStack: 2.0.1
```

### Anything else?

[terraform_exec.txt](https://github.com/localstack/localstack/files/11259059/terraform_exec.txt)
[localstack_log.txt](https://github.com/localstack/localstack/files/11259060/localstack_log.txt)

**Comment by whummer** [comment]
Thanks for reporting @tiagoposse . We have now pushed a few enhancements in #8162 which should fix the Terraform deployment of ACM certificates. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by tiagoposse** [comment]
Unfortunately the "latest" image returns
```
LocalStack supervisor: localstack process (PID 16) returned with exit code -11
LocalStack supervisor: exiting
```
when running this example

**Comment by whummer** [comment]
Thanks for the update @tiagoposse . Exit code -11 usually means "segmentation fault", which indicates a fatal error in the execution, usually caused by an invalid memory access.

This type of error is usually quite specific to the environment you're running in (operating system, CPU architecture, Docker version, etc). Can you please share a few more details about your environment? 

Also, are you seeing any more details in the logs, perhaps with `DEBUG=1` or `LS_LOG=trace` (for detailed trace logging) enabled - can you please share the logs with these configs enabled? Thanks!

**Comment by tiagoposse** [comment]
Not sure if it's the same error currently (pulled new latest and error code looks different), but facing an error still.

I'm running in docker, in an M1 macbook with Monterey 12.4.

```> docker version
Client: Docker Engine - Community
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        9fdeb9c3de
 Built:             Tue Oct 18 17:43:24 2022
 OS/Arch:           darwin/arm64
 Context:           orbstack
 Experimental:      true

Server:
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       94d3ad69cc598b5a8eb8a643d6999375953512e8
  Built:            Sun Apr 30 20:03:42 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:```

env config:
```
AWS_DEFAULT_REGION=eu-central-1
DEFAULT_REGION=eu-central-1
HOSTNAME_EXTERNAL=localhost.localstack.cloud
DOCKER_HOST=unix:///var/run/docker.sock
HOST_TMP_FOLDER=/tmp/localstack
PERSISTENCE=1
DEBUG=1
LS_LOG=trace
ENFORCE_IAM=0
```

Logs:
```
2023-05-02T09:34:16.531 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:4566/
2023-05-02T09:34:17.026 DEBUG --- [   asgi_gw_0] localstack.state.inspect   : Unable to get attribute "ec2_stores" for module "localstack_ext.services.ec2.models": "No module named 'localstack_ext.services.ec2.models'"
2023-05-02T09:34:17.026 DEBUG --- [   asgi_gw_0] localstack.state.inspect   : Unable to get attribute "ec2_stores" for module "localstack.services.ec2.models": "module 'localstack.services.ec2.models' has no attribute 'ec2_stores'"
2023-05-02T09:34:17.026 DEBUG --- [   asgi_gw_0] localstack.state.inspect   : Visiting attribute ec2_backends in module moto.ec2.models
Signal received: -2080364208, errno: 65535
################################################################################
Stack trace:
################################################################################
/opt/code/localstack/.venv/lib/python3.10/site-packages/_awscrt.cpython-310-aarch64-linux-gnu.so(aws_backtrace_print+0x4c) [0xffffa2205110]
/opt/code/localstack/.venv/lib/python3.10/site-packages/_awscrt.cpython-310-aarch64-linux-gnu.so(+0x7bd68) [0xffffa215cd68]
linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffffa3a2b790]
/opt/code/localstack/.venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so(+0x29a278) [0xffffa1a25278]
/opt/code/localstack/.venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so(+0x1def18) [0xffffa1969f18]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x168b98) [0xffffa37efb98]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x3a48) [0xffffa3844378]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x163068) [0xffffa37ea068]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_FastCallDictTstate+0x114) [0xffffa37f9924]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x177fb4) [0xffffa37fefb4]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x151164) [0xffffa37d8164]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x254) [0xffffa37b735c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x4c6c) [0xffffa384559c]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(PyVectorcall_Call+0x78) [0xffffa37c28d8]
/usr/local/lib/python3.10/lib-dynload/_pickle.cpython-310-aarch64-linux-gnu.so(+0xba50) [0xffffa09b2a50]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x169524) [0xffffa37f0524]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x3a48) [0xffffa3844378]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x164050) [0xffffa37eb050]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x172f9c) [0xffffa37f9f9c]
/usr/local/bin/../lib/libpython3.10.so.1.0(PyVectorcall_Call+0x78) [0xffffa37c28d8]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x1cb4) [0xffffa38425e4]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x163068) [0xffffa37ea068]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x3a48) [0xffffa3844378]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x163068) [0xffffa37ea068]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x172dfc) [0xffffa37f9dfc]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x88c) [0xffffa38411bc]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_FastCallDictTstate+0x64) [0xffffa37f9874]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_Call_Prepend+0x78) [0xffffa37f9b68]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x172cac) [0xffffa37f9cac]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x174) [0xffffa37b727c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x4074) [0xffffa38449a4]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_FastCallDictTstate+0x278) [0xffffa37f9a88]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_Call_Prepend+0x78) [0xffffa37f9b68]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x172cac) [0xffffa37f9cac]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyObject_Call+0x6c) [0xffffa37c2a04]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x1cb4) [0xffffa38425e4]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(PyVectorcall_Call+0x78) [0xffffa37c28d8]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x1cb4) [0xffffa38425e4]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6d8) [0xffffa3841008]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x162f5c) [0xffffa37e9f5c]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x172f08) [0xffffa37f9f08]
/usr/local/bin/../lib/libpython3.10.so.1.0(PyVectorcall_Call+0x78) [0xffffa37c28d8]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x20ef80) [0xffffa3895f80]
/usr/local/bin/../lib/libpython3.10.so.1.0(+0x200824) [0xffffa3887824]
/lib/aarch64-linux-gnu/libpthread.so.0(+0x77e4) [0xffffa36187e4]
/lib/aarch64-linux-gnu/libc.so.6(+0xcf70c) [0xffffa348a70c]
LocalStack supervisor: localstack process (PID 15) returned with exit code 255
```

**Comment by tiagoposse** [comment]
for anyone interested, the error I faced was related to persistence. Deleting the local volume and re-starting localstack fixed it

**Comment by tiagoposse** [comment]
Can confirm this is fixed

**Comment by tiagoposse** [comment]
the logs show an issued certificate, but the data field still continues indefinitely:
```
localstack.request.aws     : AWS acm.ListCertificates => 200; ListCertificatesRequest({'CertificateStatuses': ['ISSUED']}, headers={'Host': 'localhost:4566', 'User-Agent': 'APN/1.0 HashiCorp/1.0 Terraform/1.3.4 (+https://www.terraform.io) terraform-provider-aws/4.59.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.221 (go1.19.6; darwin; arm64)', 'Content-Length': '34', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20230515/eu-central-1/acm/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=4c236a81a2baf3c67abe5d065e824632e7b14835c91b47e8a762e95a8b29c3bf', 'Content-Type': 'application/x-amz-json-1.1', 'X-Amz-Date': '20230515T174119Z', 'X-Amz-Target': 'CertificateManager.ListCertificates', 'Accept-Encoding': 'gzip', 'x-localstack-tgt-api': 'acm', 'x-moto-account-id': '000000000000'}); ListCertificatesResponse({'CertificateSummaryList': [{'CertificateArn': 'arn:aws:acm:eu-central-1:000000000000:certificate/c70b70c1-b47e-482d-bd39-33669f65070b', 'DomainName': '*.example.com', 'Status': 'ISSUED', 'Type': 'AMAZON_ISSUED', 'KeyAlgorithm': 'RSA_2048', 'KeyUsages': [{'Name': 'DIGITAL_SIGNATURE'}], 'ExtendedKeyUsages': [], 'RenewalEligibility': 'INELIGIBLE', 'NotBefore': datetime.datetime(2023, 5, 15, 17, 31, 32, tzinfo=tzlocal()), 'NotAfter': datetime.datetime(2024, 5, 14, 17, 31, 32, tzinfo=tzlocal()), 'CreatedAt': datetime.datetime(2023, 5, 15, 17, 31, 32, 227322, tzinfo=tzlocal()), 'IssuedAt': datetime.datetime(2023, 5, 15, 17, 31, 32, 227322, tzinfo=tzlocal())}]}, headers={'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '465', 'x-amzn-requestid': 'TM4J6ET7JRVUANVSZF67IDEK55LF3EEFY59FGKW10DE47ZFBS8Z3', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

**Comment by alexrashed** [comment]
Hi @tiagoposse.
Sorry for the late response. I just tried to reproduce the issue with the sample (thanks for making it easy to reproduce your sample)! For me the terraform configuration can be applied just fine. It seems like the issue you have been facing has been resolved in the meantime. I'll close the issue for now, but please feel free to open a new issue if you are still experiencing any issues! Thanks!
