### ISSUE TITLE
bug: Creating SQS queue fails with botocore==1.29.127 & botocore==1.31.81

### ISSUE THREAD

**Issue by mijolabs** [localstack/localstack#8267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating an SQS queue appears to fail with AWS SDK for Python ([Boto3](https://pypi.org/project/boto3)) >= 1.26.0.

### Using Boto3 1.26.0 (released Nov 1, 2022. Latest version is 1.26.127)

Installing Boto3 1.26.0.
```shell
pip install boto3==1.26.0
```

Code creating SQS queue:
```python
from boto3 import Session

client = Session().resource("sqs", endpoint_url="http://localhost:4566")
client.create_queue(QueueName="test-queue")
```

LocalStack container log:
```
localstack  | 2023-05-05T10:18:43.915 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack  | 2023-05-05T10:18:43.917  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
localstack  | 2023-05-05T10:18:44.200 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack  | 2023-05-05T10:18:44.204  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
localstack  | 2023-05-05T10:18:44.750 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack  | 2023-05-05T10:18:44.755  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
localstack  | 2023-05-05T10:18:46.953 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack  | 2023-05-05T10:18:46.958  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
localstack  | 2023-05-05T10:18:49.182 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack  | 2023-05-05T10:18:49.184  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
```

Exception from the code:
```
botocore.exceptions.ClientError: An error occurred (500) when calling the CreateQueue operation (reached max retries: 4): <?xml version='1.0' encoding='utf-8'?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception while calling sqs with unknown operation: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).</Message></Error><RequestId>VS4YRHM46ILFR98NPJEUGO6TY1SB7N18T44DNDTIHIN21Q5CFVVY</RequestId></ErrorResponse>
```

### Using Boto3 1.25.5 (version directly prior to 1.26.0)

Installing Boto3 1.25.5
```shell
pip install boto3==1.25.5
```

Code creating SQS queue:
```python
from boto3 import Session

client = Session().resource("sqs", endpoint_url="http://localhost:4566")
client.create_queue(QueueName="test-queue")
```

LocalStack container log:
```
localstack  | 2023-05-05T10:29:30.062  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sqs.CreateQueue => 200
```

Queue created successfully from code.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Starting LocalStack in GitLab pipeline as a service with `image: localstack/localstack:latest`.

Same results when starting LocalStack 2.0.1 with a `docker-compose.yml` file locally.

### Environment

```markdown
- OS: macOS 13.3.1
- LocalStack: latest (2.0.2)
```

### Anything else?

- [This issue](https://github.com/localstack/localstack/issues/7752) seems to get a similar error message. Unsure if cause is related.
- Issue could potentially be with Boto3's underlying `botocore` library.

**Comment by stasadev** [comment]
This is because AWS has switched to another `Content-Type` in all their SDKs yesterday.

From changelog: This release enables customers to call SQS using AWS JSON-1.0 protocol.

Localstack should now include `application/x-amz-json-1.0` support for SQS.

**Comment by javiertejero** [comment]
when I tried to reproduce it happened also to me, but only if I have `botocore==1.29.127`. However with `botocore==1.29.126` and `botocore==1.29.128` seems to work fine.

what I said above was tested with both `boto3==1.26.0` and `boto3==1.26.129`

**Comment by stasadev** [comment]
This is because changes to the SQS have been rolled back. Probably, they did not expect such an impact.
Anyway, Localstack should have support for both `query` and `json`. The format may be changed again in the future.

**Comment by alexrashed** [comment]
FYI: This issue reoccurred with `botocore==1.31.81`, since `botocore` decided to finally perform the switch from `query` to `json` for SQS again.
This issue is a top priority and is being worked on in https://github.com/localstack/localstack/pull/8268.

**Comment by eau-de-la-seine** [comment]
Hi I have encoutered this problem and my solution was to come back to a stable version of the AWS client like `"@aws-sdk/client-sqs": "3.410.0",`

In the recent version of the AWS client, you have a `node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js` file containing:
```js
const parseBody = (streamBody, context) => collectBodyString(streamBody, context).then((encoded) => {
    if (encoded.length) {
        return JSON.parse(encoded);
    }
    return {};
});
```
and it breaks at `JSON.parse(encoded)` because `encoded` is a string with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
  <Error>
    <Code>InternalError</Code>
    <Message>exception while calling sqs with unknown operation: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).</Message>
  </Error>
  <RequestId>c5c0be97-f50c-4d25-a811-cdaed50149fd</RequestId>
</ErrorResponse>
```

**Comment by deangelacgn** [comment]
I started having the same issue today with `boto3==1.28.69` and LocalStack: 2.3.2. Downgrading boto3 to `1.25.5` seems to solve the issue.

**Comment by shadowhand** [comment]
As of version 3.285.2 of aws/aws-sdk (for PHP) SQS::GetQueueUrl calls to localstack fail. This means we cannot upgrade the SDK because our CI/CD servers use localstack for tests, and all builds with version 3.285.2 are failing.

The error message we see is:

```
Unable to parse error information from response - Error parsing JSON: Syntax error
```

**Comment by dmitry-weirdo** [comment]
This is a failure example for the java SDK after aws.sdk update `2.21.17` → `2.21.19`.

As we see, it's failing on `createQueue`:

```
at software.amazon.awssdk.services.sqs.DefaultSqsClient.createQueue(DefaultSqsClient.java:801)
```

Full stacktrace:
```java
[ERROR] com.mycompany.myproject.application.integration.ReleaseDocumentIT.testReleaseRecipeWithVariants -- Time elapsed: 0 s <<< ERROR!
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:552)
	at org.junit.jupiter.engine.execution.ConstructorInvocation.proceed(ConstructorInvocation.java:56)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: software.amazon.awssdk.services.sqs.model.SqsException: Service returned HTTP status code 500 (Service: Sqs, Status Code: 500, Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.sqs.DefaultSqsClient.createQueue(DefaultSqsClient.java:801)
	at com.mycompany.myproject.application.integration.ReleaseDocumentIT$Companion.createTopicAndSubscribeToIt(ReleaseDocumentIT.kt:353)
	at com.mycompany.myproject.application.integration.ReleaseDocumentIT$Companion.access$createTopicAndSubscribeToIt(ReleaseDocumentIT.kt:286)
	at com.mycompany.myproject.application.integration.ReleaseDocumentIT.<clinit>(ReleaseDocumentIT.kt:386)
	... 75 more
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Service returned HTTP status code 500 (Service: Sqs, Status Code: 500, Request ID: null)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Service returned HTTP status code 500 (Service: Sqs, Status Code: 500, Request ID: null)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 3 failure: Service returned HTTP status code 500 (Service: Sqs, Status Code: 500, Request ID: null)
```

**Comment by yonaszmerla** [comment]
Had the same issue here with `boto3==1.28.24` and `botocore==1.31.82`
Fixed by pinning `botocore==1.31.80` untill localstack releases the fix on their side 
Working with latest version of localstack `localstack==2.3.0`

**Comment by richardfearn** [comment]
The "Missing Action in request" error is also happening with AWS SDK 1.12.584+

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMessageListenerContainer' defined in class path resource [org/springframework/cloud/aws/messaging/config/annotation/SqsConfiguration.class]: Invocation of init method failed; nested exception is com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:921)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
        [...]
Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:3331)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:3297)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:3286)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1651)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1620)
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:94)
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:38)
	at org.springframework.messaging.core.CachingDestinationResolverProxy.resolveDestination(CachingDestinationResolverProxy.java:92)
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.queueAttributes(AbstractMessageListenerContainer.java:321)
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:293)
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.initialize(SimpleMessageListenerContainer.java:112)
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:268)
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.afterPropertiesSet(SimpleMessageListenerContainer.java:46)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 24 common frames omitted
```

**Comment by yonaszmerla** [comment]
Seems that it is an issue with localstack integration with latest version of botocore.
It hasn't got to do with aws version.
Try to downgrade botocore to <= 1.31.80 untill this get fixed in localstack release

**Comment by richardfearn** [comment]
> @richardfearn Seems that it is an issue with localstack integration with latest version of botocore. It hasn't got to do with aws version. Try to downgrade botocore to <= 1.31.80 untill this get fixed in localstack release

No boto involved. This is with the Java SDK. Using 1.12.584+ or 2.21.18+ results in the error

**Comment by yonaszmerla** [comment]
@richardfearn 
Assuming it's the same problem of not using the same protocol because of aws changes
You'll need to stay with AWS SDK < 1.12.584  until localstack fixes this

**Comment by saimon-moore** [comment]
Having same issue. Can confirm pinning to `botocore==1.31.80` as a workaround works:

```
pip3 install --upgrade awscli botocore==1.31.80
pip3 install --upgrade awscli-local botocore==1.31.80
```

Hopefully this gets fixed pretty quickly.

**Comment by rjacobs91** [comment]
I think the `botocore` pinning only works for `aws` cli and Python SDK calls. I'm seeing the same as @yonaszmerla where all versions of AWS Java SDK v1 are failing to create SQS queues.

**Comment by bentsku** [comment]
> I think the `botocore` pinning only works for `aws` cli and Python SDK calls. I'm seeing the same as @yonaszmerla where all versions of AWS Java SDK v1 are failing to create SQS queues.

That should not happen, it is only the latest versions of AWS SDK that switched to the new `json` protocol for SQS. Previous ones are still working with XML, and nothing changed in that regard. Which SDK version are you using, and which LocalStack version? Thanks!

**Comment by rjacobs91** [comment]
For clarity, I'm using docker for testing interactions with localstack and more specifically the [testcontainers module of localstack](https://java.testcontainers.org/modules/localstack/).
I've pinned my localstack docker version to 2.2.0 and am using AWS SDK version v1 (1.12.522)

**Comment by bentsku** [comment]
Here is the list with all the SDK versions where the issue will start appearing:
Language | SDK client repository | Required SDK client version
--- | --- | ---
C++ |  [aws/aws-sdk-cpp](https://github.com/aws/aws-sdk-cpp) | [1.11.98](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.198)
Golang 1.x | [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) | [v1.47.7](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.7)
Golang 2.x |  [aws/aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) | [v1.28.0](https://github.com/aws/aws-sdk-go-v2/blob/release-2023-11-09/service/sqs/CHANGELOG.md#v1270-2023-11-09)
Java 1.x | [aws/aws-sdk-java](https://github.com/aws/aws-sdk-java) |  [1.12.585](https://github.com/aws/aws-sdk-java/releases/tag/1.12.585)
Java 2.x |  [aws/aws-sdk-java-v2](https://github.com/aws/aws-sdk-java-v2) | [2.21.19](https://github.com/aws/aws-sdk-java/releases/tag/2.21.19)
JavaScript v2.x | [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) |  [v2.1492.0](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.1492.0)
JavaScript v3.x |  [aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3) | [v3.447.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.447.0)
.NET | [aws/aws-sdk-net](https://github.com/aws/aws-sdk-net) |  [3.7.681.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.681.0)
PHP | [aws/aws-sdk-php](https://github.com/aws/aws-sdk-php) | [3.285.2](https://github.com/aws/aws-sdk-php/releases/tag/3.285.2)
Python-boto3 | [boto/boto3](https://github.com/boto/boto3) | [1.28.82](https://github.com/boto/boto3/releases/tag/1.28.82)
Python-botocore |  [boto/botocore](https://github.com/boto/botocore/) | [1.31.82](https://github.com/boto/botocore/releases/tag/1.31.82)
awscli |  [AWS CLI](https://github.com/aws/aws-cli) | [1.29.82](https://github.com/aws/aws-cli/releases/tag/1.29.82)
Ruby | [aws/aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) |  [1.67.0](https://rubygems.org/gems/aws-sdk-sqs/versions/1.67.0)

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html#json-protocol-supported-languages

Please note that it's possible the issue is present in some previous versions of those, for example Botocore is announced as `1.31.82` on AWS list, but we know that the issue is already present in `1.31.81`, however it contained a bug with SQS they quickly fixed. 

We're still actively working to fix this issue, and will keep you posted here for progress. Thanks!

**Comment by gombosg** [comment]
Seems to work with `localstack:latest` as you suggested in #9610 @bentsku ! ([current](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-635a631bbfa6ebd150276ca3f3177804834c9a255fbc738a55c4bf6a47c577b8?context=explore))

**Comment by alexrashed** [comment]
Thanks @gombosg! This issue has been fixed with the merge of #8268. The fix is already contained in `localstack/localstack:latest` as well as `localstack/localstack-pro:latest`. Thanks again to @bentsku for helping to bring this over the line. 🦸🏽 I will close this issue now.

It seems like `botocore` is still addressing some remaining issues on their side with the protocol switch (like some specifics with the error parsing), which means things are still moving a bit. If you experience any issue related to this, please create a new issue and link this one.
Thanks everyone for your patience, sorry again for the inconvenience (but this was q

**Comment by gatchan0807** [comment]
Nice to meet you. Thank you for your prompt release of the `latest` version, which contains the bug fixes.

I have one question.When are you planning to release a version (I think it will be `2.3.3`) that fixes this problem?

I am wondering if I should submit a PR to change the `2.3` designation to `latest` for use in our environment. I apologize for the detail of this question, but I would appreciate it if you could let me know.
Thanks.

**Comment by dfangl** [comment]
Hi @gatchan0807 !
Version 3.0 will be released this week (https://github.com/localstack/localstack/issues/9519), which will be the next tagged version including these fixes.

**Comment by petrovskyyanton** [comment]
> Seems to work with `localstack:latest` as you suggested in #9610 @bentsku ! ([current](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-635a631bbfa6ebd150276ca3f3177804834c9a255fbc738a55c4bf6a47c577b8?context=explore))

Can you please say which versions of boto3 and botocore work?

**Comment by petrovskyyanton** [comment]
> Seems to work with `localstack:latest` as you suggested in #9610 @bentsku ! ([current](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-635a631bbfa6ebd150276ca3f3177804834c9a255fbc738a55c4bf6a47c577b8?context=explore))

Can you please say which versions of boto3 and botocore work?

**Comment by mickeKr** [comment]
Hi, 
we are still seeing failures for the combination of `localstack/localstack:latest` and `aws-sdk-java` `1.12.584`.
Is it only us? 🙄

**Comment by yevhen-dyachenko-papernest** [comment]
> Hi, we are still seeing failures for the combination of `localstack/localstack:latest` and `aws-sdk-java` `1.12.584` and above. Is it only us? 🙄
> 
> ```
> 
> 2023-11-13 11:39:22 2023-11-13T10:39:22.386 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
> 2023-11-13 11:39:22 2023-11-13T10:39:22.387  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
> ```

You are not alone

**Comment by alexrashed** [comment]
@mickeKr and @yevhen-dyachenko-papernest: 
Could you maybe post a small minimal-reproducible-sample here such that we can check your issue?

**Comment by gatchan0807** [comment]
> Hi @gatchan0807 ! Version 3.0 will be released this week (#9519), which will be the next tagged version including these fixes.

Thanks for your reply!

By the way, are there any plans to include this fix in the 2.x series version?
We are hoping to take enough time to update to the 3.x series, so I was just asking because I would be happy to have a 2.x series version with this fix for a temporary fix.

If not, we will work around it by fixing the version on the aws-cli side, so don't worry about it.

**Comment by mickeKr** [comment]
> @mickeKr and @yevhen-dyachenko-papernest: Could you maybe post a small minimal-reproducible-sample here such that we can check your issue?
```
object LocalStackRunner :
    LocalStackContainer(DockerImageName.parse("localstack/localstack:latest")) {
    val sqsClient: AmazonSQS
    val config: MessagingConfiguration

    private val snsClient: AmazonSNS
    private val snsConsumer: String

    init {

        withServices(SQS, SNS)
        start()
        waitUntilContainerStarted()

        sqsClient = AmazonSQSClient
            .builder()
            .withEndpointConfiguration(
                EndpointConfiguration(this.getEndpointOverride(SQS).toString(), this.region)
            )
            .withCredentials(AWSStaticCredentialsProvider(BasicAWSCredentials(accessKey, secretKey)))
            .build()
        snsClient = AmazonSNSClient
            .builder()
            .withEndpointConfiguration(
                EndpointConfiguration(this.getEndpointOverride(SNS).toString(), this.region)
            )
            .withCredentials(AWSStaticCredentialsProvider(BasicAWSCredentials(accessKey, secretKey)))
            .build()

        snsConsumer = sqsClient.createQueue ("customer").queueUrl
        ```

**Comment by alexrashed** [comment]
@gatchan0807 Unfortunately, there are currently no plans in creating a bugfix release / backporting this fix.
But should be able to circumvent this issue by limiting the AWS SDK / CLI version you are using.

@mickeKr Thanks for providing the example, we'll take a look right away.

**Comment by gatchan0807** [comment]
I see, thank you a lot!
I will try it that way.

**Comment by alexrashed** [comment]
@mickeKr @yevhen-dyachenko-papernest
I just tried your sample with the latest AWS Java SDK and the latest Docker images for LocalStack Community and Pro.
Both is working perfectly fine for me. Here's the Java code I used to test this:
```java
package cloud.localstack.demos.sqs;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClient;
import com.amazonaws.services.sqs.model.CreateQueueResult;

public class Main {

    public static void main(String[] args) {
        AmazonSQS sqsClient = AmazonSQSClient
                .builder()
                .withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration("http://localhost.localstack.cloud:4566", "us-east-1")
                )
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("test", "test")))
                .build();
        CreateQueueResult queue = sqsClient.createQueue("test");
        System.out.println(queue.getQueueUrl());
    }
}
```

Here's the maven `pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>aws-java-sdk-sqs-test</artifactId>
    <groupId>cloud.localstack</groupId>
    <version>1.0-SNAPSHOT</version>
    <name>AWS Java SDK SQS Test</name>

    <properties>
        <exec.mainClass>cloud.localstack.demos.sqs.Main</exec.mainClass>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sqs</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.12.587</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
```


Please make sure to explicitly pull your Docker image, since they are cached locally:
```bash
docker pull localstack/localstack:latest
docker pull localstack/localstack-pro:latest
```

If your issue still persists, please create a new issue (as outlined in my comment above).
Thanks!

**Comment by mickeKr** [comment]
@alexrashed , apologies, it was of course a stale `latest` ( `stalatest`?) image version that was the culprit. 
Now I'm facing https://github.com/localstack/localstack/pull/9607 but a fix is on its way If I'm not mistaken.

**Comment by adiberk** [comment]
Hi can someone explain how to fix this bug as I don't want to upgrade to v3.0.0.  And this is a huge issue in our development
I am using localstack and my app is in python

**Comment by yonaszmerla** [comment]
@adiberk 
you need to pin your botocore version to <= 1.31.80 as it is a change in botocore==1.31.81 and further that breaks conectivity with localstack < 3.0.0

**Comment by alexrashed** [comment]
As mentioned above, you can just pin your client to a version which does not send the new JSON format.
@bentsku created an excellent list of clients with the version where they switched to the new format:
https://github.com/localstack/localstack/issues/8267#issuecomment-1806421471

This is not an issue created in LocalStack, this is your client switching to a completely new protocol for SQS.

**Comment by adiberk** [comment]
=

> @adiberk you need to pin your botocore version to <= 1.31.80 as it is a change in botocore==1.31.81 and further that breaks conectivity with localstack < 3.0.0

Got it.  I guess my question was this
I tried pinning botocor in my python application and it  didn't work.
I then tried running the following in my dockerfile in my localstack container pip3 install --upgrade awscli botocore==1.31.80 && pip3 install --upgrade awscli-local botocore==1.31.80

In both scenarios I was still getting the error. Am I missing something?  Do I need to make sure localstack awslocal is using the correct version of botocore mentioned? Is it just my app?

**Comment by alexrashed** [comment]
You need to make sure that the client which talks to LocalStack is using the old version of the client.
So if you get the error when sending a request _from_ your python application, you need to make sure that the client _in your python application_ is pinned to the older version.
If you issue persists, please create a new issue where you exactly describe your setup. Then we can take a separate look at this.
Thanks!

**Comment by adiberk** [comment]
@yonaszmerla Got it. I guess my question was this
I tried pinning botocor in my python application and it didn't work.
I then tried running the following in my dockerfile in my localstack container pip3 install --upgrade awscli botocore==1.31.80 && pip3 install --upgrade awscli-local botocore==1.31.80

In both scenarios I was still getting the error. Am I missing something? Do I need to make sure localstack awslocal is using the correct version of botocore mentioned - if so how can I ensure that? Is it just my app?

**Comment by hashtagchris** [comment]
> You need to make sure that the client which talks to LocalStack is using the old version of the client.

In case it helps anyone:

I've previously used `pip install awscli-local[ver1]` to install `awslocal` along with the `awscli`, per https://github.com/localstack/awscli-local. To get `awslocal` working again ahead of updating localstack, I ran `pip install awscli==1.29.80`.

**Comment by sawilde** [comment]
@alexrashed If we want to keep using the latest AWS packages, and the features they enable/expose, do we need to switch localstack versions from 2 to 3?

**Comment by alexrashed** [comment]
Yes, exactly. LocalStack 3.0 will be released on Thursday, 16th of November.
You can find all details here in the release announcement: https://github.com/localstack/localstack/issues/9519

**Comment by saimon-moore** [comment]
I'm seeing this also with the nodejs sdk v3.262.0

**Comment by alexrashed** [comment]
@bentsku created an excellent list of clients with the version where they switched to the new format:
https://github.com/localstack/localstack/issues/8267#issuecomment-1806421471

If you are already using an older version, then the issue you might be seeing is not related to this issue. Please create another issue in this case. Thanks!

**Comment by saimon-moore** [comment]
I guess it's another issue because nodejs is not on that list. I'll try and dig a bit deeper to see if I can get more data. 

(But it's the exact same error as for when we are creating sqs queues via the cli which I fixed by pinning botocore so that's weird).

**Comment by shadowhand** [comment]
> I guess it's another issue because nodejs is not on that list.

NodeJS is JavaScript. 🙃

**Comment by saimon-moore** [comment]
Yeah I was blind ha ha

**Comment by alexrashed** [comment]
Are you sure that you pulled `localstack/localstack:latest` recently? This tag is continuously updated and cached on your machine. You can do so by execution `docker pull localstack/localstack:latest`.

**Comment by bentsku** [comment]
AWS does not respond by default to the `json` protocol either, you need to set the `Content-Type` header as specified in the documentation:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-making-api-requests-json.html

> The following is an example of an HTTP header with X-Amz-Target set to AmazonSQS.<operationName>, and an HTTP header with Content-Type set to application/x-amz-json-1.0.

> Both HTTP headers X-Amz-Target and Content-Type are required.
Your HTTP client might add other items to the HTTP request, according to the client's HTTP version.

**Comment by nikolay-kornev** [comment]
So, to be sure, I pulled `localstack/localstack:latest` just now. 
```
Digest: sha256:a36a013dc03c62e7f7db51ceba29ba24b76cd1e73fab72f4b75b16ad58a4db52
Status: Downloaded newer image for localstack/localstack:latest
docker.io/localstack/localstack:latest
```

Receiving message works using `aws/aws-sdk-php:3.284.0`, `aws/aws-sdk-php:3.284.1`, `aws/aws-sdk-php:3.285.0`.

It breaks once I upgrade to `aws/aws-sdk-php:3.285.1`. I assume this is when default protocol used by AWS PHP SDK is changing to `json`.

Thus the question - for whatever reason, LocalStack still attempts to handle request as if it were using `query` protocol.

**Comment by alexrashed** [comment]
I just verified the SQS operations to create a queue, send a message, and receive a message. All sends and receives JSON perfectly fine, using the latest botocore (python client).
If you are still facing any issues with the latest versions and images, please create a new issue with an exact description of your setup and a minimum-reproducible example.
Thanks!

**Comment by bentsku** [comment]
@nikolay-kornev the PHP SDK issue should be now solved in the `latest` image, we investigated and there was an issue in the SDK itself not following the specifications. If there's still anything, feel free to open new issue with your SDK version. Thanks!

**Comment by nikolay-kornev** [comment]
@bentsku Thanks for the fix! I pulled latest `localstack/localstack:latest` image, and now it is working fine with AWS PHP SDK.

**Comment by joemcbride** [comment]
We were getting similar errors with localstack 2.3.2 and terraform aws provider >= 5.25.0. Pinning terraform aws provider 5.24.0 fixed our issue.

**Comment by adiberk** [comment]
Just curios - will localstack2.3.2 still have this issue with latest botocore and boto3? Right now we have our libs pinned to working versions from a while ago. However I have come to point where I may need to update the boto libs. But I can't do it if localstack 2.3.2 is completely incompatible due to this protocol error.  (I can't update our teams localstack due to severe infrastructure issues if we ugprade)
